<?php

if ($this->script) {    // Run script and return (no form is displayed)
    echo "<script>" . PHP_EOL;
    echo $this->script . PHP_EOL;
    echo "</script>" . PHP_EOL;
    return;
}

$form = $this->form;
$security = $form->get('security');
$box = $form->get('box');
$uid = $form->get('uid');

?>

<?php if ($this->parseError): ?>
    <script>
        bsAlert('<?= $this->translate('CAN_NOT_CREATE_CAMPAIGN') ?>');
    </script>
    <?php return ?>
<?php else: ?>
    <form class="form-horizontal" name="<?= $form->getName() ?>" onsubmit="return false"
          method="<?= $form->getAttribute('method') ?>"
          action="<?= $this->basePath('/admin/mailbox/create-campaign') ?>">

        <input type="hidden"
               name="<?= $security->getName() ?>"
               value="<?= $security->getValue() ?>">

        <input type="hidden"
               name="<?= $box->getName() ?>"
               value="<?= $box->getValue() ?>">

        <input type="hidden"
               name="<?= $uid->getName() ?>"
               value="<?= $uid->getValue() ?>">

        <?php foreach (array_merge($this->messages, $security->getMessages()) as $msg): ?>
            <div class="alert alert-danger">
                <center><?= $this->escapeHtml($this->translate($msg)) ?></center>
            </div>
        <?php endforeach ?>

        <p><?= $this->translate('CONFIRM_CREATE_CAMPAIGN') ?></p>
    </form>
<?php endif ?>

<script>
    var modal = $('#modal-form');

    initModalForm(modal);                   // See /js/app.js 

    if (!modal.is(':visible'))
        modal.modal('show');

    setFormFocus(modal.find('form'));       // See /js/app.js
</script>
