<?php

    $this->layout()->activePage = 'mailbox';

?>
<div class="container">
    <div class="row">
        <div class="col-sm-offset-3 col-sm-9">
            <h1><span id="page-title"><?= $this->translate('Mailbox') ?></span></h1>
        </div>
    </div>

    <div class="row">
        <div class="col-sm-3">
            <div data-sidebar="sm">
                <div id="actions-panel" class="panel panel-default">
                    <div class="panel-heading">
                        <h3 class="panel-title"><?= $this->translate('Table actions') ?></h3>
                    </div>
                    <div class="panel-body button-panel">
                        <button id="template-button" class="btn btn-primary disabled" disabled="disabled" onclick="createCampaign()">
                            <?= $this->translate('Use as template') ?>
                        </button>
                        <hr>
                        <button id="delete-button" class="btn btn-default disabled" disabled="disabled" onclick="deleteLetter()">
                            <?= $this->translate('Delete letter') ?>
                        </button>
                        <hr>
                        <button id="reanalyze-button" class="btn btn-default" disabled="disabled" onclick="reanalyzeLetter()">
                            <?= $this->translate('Reanalyze letter') ?>
                        </button>
                    </div>
                </div>
            </div>
        </div>

        <div class="col-sm-9">
            <div role="tabpanel">
                <ul class="nav nav-tabs" role="tablist">
                    <?php $first = true; ?>
                    <?php foreach ($this->mailboxes as $box): ?>
                        <li role="presentation" class="<?= $first ? 'active' : '' ?>">
                            <a id="<?= strtolower($box['id']) ?>-tab" href="#tab-<?= $box['id'] ?>" aria-controls="<?= $box['id'] ?>" role="tab" data-toggle="tab">
                                    <?= $this->translate($box['name']) ?>
                                &nbsp;
                            </a>
                            <script>
                                $('a[href=#tab-<?= $box['id'] ?>]').on('show.bs.tab', function () {
                                    selectedBox = '<?= $box['id'] ?>';
                                    updateActions('<?= $box['id'] ?>');
                                });
                            </script>
                        </li>
                        <?php $first = false; ?>
                    <?php endforeach ?>
                </ul>
                <div class="tab-content">
                    <?php $first = true; ?>
                    <?php foreach ($this->mailboxes as $box): ?>
                        <div id="tab-<?= $box['id'] ?>" role="tabpanel" class="tab-pane <?= $first ? 'active' : '' ?>">
                            <div id="table-<?= $box['id'] ?>" class="table-frame"></div>
                            <script>
                                $('#table-<?= $box['id'] ?>').dynamicTable({
                                    url: '<?= $this->basePath('/admin/mailbox/letter-table') ?>'
                                        + '?box=<?= urlencode($box['id']) ?>',
                                    row_id_column: 'uid',
                                    sort_column: 'date',
                                    sort_dir: 'desc',
                                    loader_image: '<?= $this->basePath('/img/loader.gif') ?>',
                                    strings: dynamicTableStrings,
                                    mapper: function (row) {
                                        if (row['subject'].trim().length == 0)
                                            row['subject'] = '<?= $this->translate('(No subject)') ?>';

                                        var box = "<?= str_replace("'", '\\\'', $this->escapeHtml($box['name'])) ?>";
                                        row['subject'] = '<a href="javascript:void(0)" onclick="openLetter(\'' + box + '\', ' + row['uid'] + ')">' + row['subject'] + '</a>';


                                        if (row['date'] != null) {
                                            var m = moment.unix(row['date']).local();
                                            row['date'] = m.format('YYYY-MM-DD HH:mm:ss');
                                        }

                                        return row;
                                    },
                                });
                                $('#table-<?= $box['id'] ?>').on('dt.selected', function () {
                                    updateActions('<?= $box['id'] ?>');
                                });
                                $('#table-<?= $box['id'] ?>').on('dt.deselected', function () {
                                    updateActions('<?= $box['id'] ?>');
                                });
                            </script>
                        </div>
                        <?php $first = false; ?>
                    <?php endforeach ?>
                </div>
            </div>
        <div>
    </div>
</div>

<div id="letter-modal" class="modal">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">
                    <span aria-hidden="true">&times;</span>
                    <span class="sr-only"><?= $this->translate('Close') ?></span>
                </button>
                <h4 class="modal-title"></h4>
            </div>
            <div class="modal-body">
                <div role="tabpanel">
                    <ul class="nav nav-tabs" role="tablist">
                        <li role="presentation" class="active">
                            <a href="#html" aria-controls="html" role="tab" data-toggle="tab">
                                <?= $this->translate('HTML') ?>
                            </a>
                        </li>
                        <li role="presentation">
                            <a href="#text" aria-controls="text" role="tab" data-toggle="tab">
                                <?= $this->translate('Text') ?>
                            </a>
                        </li>
                        <li role="presentation">
                            <a href="#attachments" aria-controls="attachments" role="tab" data-toggle="tab">
                                <?= $this->translate('Attachments') ?>
                            </a>
                        </li>
                        <li role="presentation">
                            <a href="#log" aria-controls="log" role="tab" data-toggle="tab">
                                <?= $this->translate('Analysis log') ?>
                            </a>
                        </li>
                        <li role="presentation">
                            <a href="#source" aria-controls="source" role="tab" data-toggle="tab">
                                <?= $this->translate('Source') ?>
                            </a>
                        </li>
                    </ul>
                    <div class="tab-content">
                        <div id="html" role="tabpanel" class="tab-pane active">
                            <div class="tab-pane-loader"></div>
                            <iframe class="letter-frame"></iframe>
                        </div>
                        <div id="text" role="tabpanel" class="tab-pane">
                            <div class="tab-pane-loader"></div>
                            <div class="letter-frame"></div>
                        </div>
                        <div id="attachments" role="tabpanel" class="tab-pane">
                            <div class="tab-pane-loader"></div>
                            <div class="letter-frame"></div>
                        </div>
                        <div id="log" role="tabpanel" class="tab-pane">
                            <div class="tab-pane-loader"></div>
                            <div class="letter-frame"></div>
                        </div>
                        <div id="source" role="tabpanel" class="tab-pane">
                            <div class="tab-pane-loader"></div>
                            <div class="letter-frame"></div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="modal-footer">
                <div class="pull-left">
                    <strong>
                        <?= $this->translate('Letter check status') ?>:
                        <span id="parse-status"><?= $this->translate('Loading...') ?></span>
                    </strong>
                </div>
                <button class="btn btn-primary" data-dismiss="modal">
                    <?= $this->translate('Close') ?>
                </button>
            </div>
        </div>
    </div>
</div>

<script>
    var selectedBox = '<?= $this->mailboxes[0]['id'] ?>';

    function updateActions(id) {
        var table = $('#table-' + id).data('dynamicTable');
        var selected = table.getSelected();

        if (selected == 'all' || selected.length > 1) {
            $('#template-button')
                .attr('disabled', 'disabled')
                .addClass('disabled');
            $('#delete-button')
                .removeAttr('disabled')
                .removeClass('disabled');
            $('#reanalyze-button')
                .removeAttr('disabled')
                .removeClass('disabled');
        } else if (selected.length) {
            $('#actions-panel').find('button')
                .removeAttr('disabled')
                .removeClass('disabled');
        } else {
            $('#actions-panel').find('button')
                .attr('disabled', 'disabled')
                .addClass('disabled');
        }
    }

    function reloadTables() {
        <?php foreach ($this->mailboxes as $box): ?>
            var table = $('#table-<?= $box['id'] ?>').data('dynamicTable');
            table.refresh();
        <?php endforeach ?>
    }

    function openLetter(box, uid) {
        $('#letter-modal .modal-title').text('<?= $this->translate('Loading...') ?>');
        $('#letter-modal .letter-frame').hide();
        $('#letter-modal .tab-pane-loader').show();

        $('#letter-modal').modal('show');

        $.getJSON(
            '<?= $this->basePath('/admin/mailbox/letter') ?>',
            {
                box: box,
                uid: uid,
            },
            function (data) {
                var iframeContext = $('#html iframe')[0].contentWindow.document;
                $('html', iframeContext).html(data.html);
                $('#text .letter-frame').html(data.text);
                $('#attachments .letter-frame').html(data.attachments);
                $('#log .letter-frame').html(data.log);
                $('#source .letter-frame').html(data.source);

                $('#letter-modal .modal-title').html(data.subject);
                if (data.error === false)
                    $('#parse-status').html('<span class="text-success"><?= $this->translate('Success') ?></span>');
                else if (data.error == 'analysis')
                    $('#parse-status').html('<span class="text-danger"><?= $this->translate('Analysis error') ?></span>');
                else if (data.error == 'syntax')
                    $('#parse-status').html('<span class="text-danger"><?= $this->translate('Syntax error') ?></span>');
                $('#letter-modal .tab-pane-loader').hide();
                $('#letter-modal .letter-frame').show();
            }
        );
    }

    function createCampaign() {
        var table = $('#table-' + selectedBox).data('dynamicTable');
        var selected = table.getSelected();
        if (selected.length == 0)
            return;

        window.location = '<?= $this->basePath('/admin/campaign/create') ?>'
            + '?box=' + selectedBox
            + '&uid=' + (selected == 'all' ? '_all' : selected.join(','));
    }

    function deleteLetter() {
        var table = $('#table-' + selectedBox).data('dynamicTable');
        var selected = table.getSelected();
        if (selected.length == 0)
            return;

        $.ajax({
            url: '<?= $this->basePath('/admin/mailbox/delete-letter') ?>',
            data: {
                box: selectedBox,
                uid: selected == 'all' ? '_all' : selected.join(',')
            },
            success: function (html) {
                var modal = $('#modal-form');
                modal.find('.modal-title').text('<?= $this->translate('Delete letter') ?>');
                modal.find('button[type=submit]').text('<?= $this->translate('Delete') ?>');
                modal.find('.modal-body').html(html);
            }
        });
    }

    function reanalyzeLetter() {
        var table = $('#table-' + selectedBox).data('dynamicTable');
        var selected = table.getSelected();
        if (selected.length == 0)
            return;

        $.ajax({
            url: '<?= $this->basePath('/admin/mailbox/reanalyze-letter') ?>',
            data: {
                box: selectedBox,
                uid: selected == 'all' ? '_all' : selected.join(',')
            },
            success: function (html) {
                var modal = $('#modal-form');
                modal.find('.modal-title').text('<?= $this->translate('Reanalyze letter') ?>');
                modal.find('button[type=submit]').text('<?= $this->translate('Execute') ?>');
                modal.find('.modal-body').html(html);
            }
        });
    }

    var tour = new Tour({
        name: 'mailbox',
        template: '<?= $this->translate('TOUR_TEMPLATE') ?>',
        steps: [
            {
                element: "#mailbox-navbar",
                placement: "bottom",
                title: "<?= str_replace('"', "'", $this->translate('Mailbox')) ?>",
                content: "<?= str_replace('"', "'", $this->translate('TOUR_MAILBOX_INTRO')) ?>"
            },
            {
                element: "#incoming-tab",
                placement: "bottom",
                title: "<?= str_replace('"', "'", $this->translate('Mailbox')) ?>",
                content: "<?= str_replace('"', "'", $this->translate('TOUR_MAILBOX_INCOMING')) ?>"
            },
            {
                element: "#replies-tab",
                placement: "bottom",
                title: "<?= str_replace('"', "'", $this->translate('Mailbox')) ?>",
                content: "<?= str_replace('"', "'", $this->translate('TOUR_MAILBOX_REPLIES')) ?>"
            },
            {
                element: "#bounces-tab",
                placement: "bottom",
                title: "<?= str_replace('"', "'", $this->translate('Mailbox')) ?>",
                content: "<?= str_replace('"', "'", $this->translate('TOUR_MAILBOX_BOUNCES')) ?>"
            },
            {
                element: "#template-button",
                placement: "right",
                title: "<?= str_replace('"', "'", $this->translate('Mailbox')) ?>",
                content: "<?= str_replace('"', '"', $this->translate('TOUR_MAILBOX_TEMPLATE')) ?>"
            },
        ]
    });

    $(document).ready(function () {
        tour.init().start();
        $('#tour-button')
            .on('click', function () { tour.restart(); })
            .parent().show();
    });
</script>
