<?php

    $this->layout()->activePage = 'mailbox';

?>
<div class="container">
    <div class="row">
        <div class="col-sm-offset-3 col-sm-9">
            <h1><span id="page-title"><?= $this->translate('Mailbox') ?></span></h1>
        </div>
    </div>

    <div class="row">
        <div class="col-sm-3">
            <div data-sidebar="sm">
                <div id="actions-panel" class="panel panel-default">
                    <div class="panel-heading">
                        <h3 class="panel-title"><?= $this->translate('Table actions') ?></h3>
                    </div>
                    <div class="panel-body button-panel">
                        <button id="template-button" class="btn btn-primary disabled" disabled="disabled" onclick="createCampaign()">
                            <?= $this->translate('Use as template') ?>
                        </button>
                        <hr>
                        <button id="delete-button" class="btn btn-default disabled" disabled="disabled" onclick="deleteLetter()">
                            <?= $this->translate('Delete letter') ?>
                        </button>
                        <hr>
                        <button id="reanalyze-button" class="btn btn-default" disabled="disabled" onclick="reanalyzeLetter()">
                            <?= $this->translate('Reanalyze letter') ?>
                        </button>
                    </div>
                </div>
            </div>
        </div>

        <div class="col-sm-9">
            <div role="tabpanel">
                <p>
                    <?= $this->translate('System email address') ?>:
                    <span id="system-address">
                        <strong><?= $this->ourEmail ?></strong>
                    </span>
                </p>
                <ul class="nav nav-tabs" role="tablist">
                    <?php $first = true; ?>
                    <?php foreach ($this->mailboxes as $box): ?>
                        <li role="presentation" class="<?= $first ? 'active' : '' ?>">
                            <a id="<?= strtolower($box['id']) ?>-tab" href="#tab-<?= $box['id'] ?>" aria-controls="<?= $box['id'] ?>" role="tab" data-toggle="tab">
                                <?= $this->translate($box['name']) ?>
                                &nbsp;
                                <span id="badge-<?= $box['id'] ?>" class="badge"></span>
                            </a>
                            <script>
                                $('a[href=#tab-<?= $box['id'] ?>]').on('show.bs.tab', function () {
                                    selectedBox = '<?= $box['id'] ?>';
                                    updateActions('<?= $box['id'] ?>');
                                });
                            </script>
                        </li>
                        <?php $first = false; ?>
                    <?php endforeach ?>
                </ul>
                <div class="tab-content">
                    <?php $first = true; ?>
                    <?php foreach ($this->mailboxes as $box): ?>
                        <div id="tab-<?= $box['id'] ?>" role="tabpanel" class="tab-pane <?= $first ? 'active' : '' ?>">
                            <div id="table-<?= $box['id'] ?>" class="table-frame"></div>
                            <script>
                                $('#table-<?= $box['id'] ?>').dynamicTable({
                                    url: '<?= $this->basePath('/admin/mailbox/letter-table') ?>'
                                        + '?box=<?= urlencode($box['id']) ?>',
                                    row_id_column: 'uid',
                                    sort_column: 'date',
                                    sort_dir: 'desc',
                                    loader_image: '<?= $this->basePath('/img/loader.gif') ?>',
                                    strings: dynamicTableStrings,
                                    mapper: function (row) {
                                        if (row['subject'].trim().length == 0)
                                            row['subject'] = '<?= $this->translate('(No subject)') ?>';

                                        var box = "<?= str_replace("'", '\\\'', $this->escapeHtml($box['name'])) ?>";
                                        row['subject'] = '<a href="javascript:void(0)" onclick="openLetter({ box: \'' + box + '\', uid: ' + row['uid'] + ' })">' + row['subject'] + '</a>';

                                        if (row['date'] != null) {
                                            var m = moment.unix(row['date']).local();
                                            row['date'] = m.format('<?= $this->translate('GENERIC_MOMENT_FORMAT') ?>');
                                        }

                                        if (!row['seen']) {
                                            row['uid'] = '<strong>' + row['uid'] + '</strong>';
                                            row['date'] = '<strong>' + row['date'] + '</strong>';
                                            row['from'] = '<strong>' + row['from'] + '</strong>';
                                            row['subject'] = '<strong>' + row['subject'] + '</strong>';
                                        }

                                        return row;
                                    },
                                });
                                $('#table-<?= $box['id'] ?>').on('dt.selected', function () {
                                    updateActions('<?= $box['id'] ?>');
                                });
                                $('#table-<?= $box['id'] ?>').on('dt.deselected', function () {
                                    updateActions('<?= $box['id'] ?>');
                                });
                                $('#table-<?= $box['id'] ?>').on('dt.loaded', function () {
                                    $.ajax({
                                        url: '<?= $this->basePath('/admin/mailbox/count-new') ?>',
                                        data: {
                                            box: '<?= $box['id'] ?>',
                                        },
                                        success: function (data) {
                                            $('#badge-<?= $box['id'] ?>').text(data.num ? data.num : '');
                                        }
                                    });
                                });

                                $.ajax({
                                    url: '<?= $this->basePath('/admin/mailbox/count-new') ?>',
                                    data: {
                                        box: '<?= $box['id'] ?>',
                                    },
                                    success: function (data) {
                                        $('#badge-<?= $box['id'] ?>').text(data.num ? data.num : '');
                                    }
                                });
                            </script>
                        </div>
                        <?php $first = false; ?>
                    <?php endforeach ?>
                </div>
            </div>
        <div>
    </div>
</div>

<script>
    var selectedBox = '<?= $this->mailboxes[0]['id'] ?>';

    function updateActions(id) {
        var table = $('#table-' + id).data('dynamicTable');
        var selected = table.getSelected();

        if (selected.length) {
            $('#actions-panel').find('button')
                .removeAttr('disabled')
                .removeClass('disabled');
        } else {
            $('#actions-panel').find('button')
                .attr('disabled', 'disabled')
                .addClass('disabled');
        }
    }

    function reloadTables() {
        <?php foreach ($this->mailboxes as $box): ?>
            var table = $('#table-<?= $box['id'] ?>').data('dynamicTable');
            table.refresh();
        <?php endforeach ?>
    }

    function createCampaign() {
        var table = $('#table-' + selectedBox).data('dynamicTable');
        var selected = table.getSelected();
        if (selected.length == 0)
            return;

        $.ajax({
            url: '<?= $this->basePath('/admin/mailbox/create-campaign') ?>',
            data: {
                box: selectedBox,
                uid: selected == 'all' ? '_all' : selected.join(',')
            },
            success: function (html) {
                var modal = $('#modal-form');
                modal.find('.modal-title').text('<?= $this->translate('Create campaign') ?>');
                modal.find('button[type=submit]').text('<?= $this->translate('Create') ?>');
                modal.find('.modal-body').html(html);
            }
        });
    }

    function deleteLetter() {
        var table = $('#table-' + selectedBox).data('dynamicTable');
        var selected = table.getSelected();
        if (selected.length == 0)
            return;

        $.ajax({
            url: '<?= $this->basePath('/admin/mailbox/delete-letter') ?>',
            data: {
                box: selectedBox,
                uid: selected == 'all' ? '_all' : selected.join(',')
            },
            success: function (html) {
                var modal = $('#modal-form');
                modal.find('.modal-title').text('<?= $this->translate('Delete letter') ?>');
                modal.find('button[type=submit]').text('<?= $this->translate('Delete') ?>');
                modal.find('.modal-body').html(html);
            }
        });
    }

    function reanalyzeLetter() {
        var table = $('#table-' + selectedBox).data('dynamicTable');
        var selected = table.getSelected();
        if (selected.length == 0)
            return;

        $.ajax({
            url: '<?= $this->basePath('/admin/mailbox/reanalyze-letter') ?>',
            data: {
                box: selectedBox,
                uid: selected == 'all' ? '_all' : selected.join(',')
            },
            success: function (html) {
                var modal = $('#modal-form');
                modal.find('.modal-title').text('<?= $this->translate('Reanalyze letter') ?>');
                modal.find('button[type=submit]').text('<?= $this->translate('Execute') ?>');
                modal.find('.modal-body').html(html);
            }
        });
    }

    var tour = new Tour({
        name: 'mailbox',
        template: '<?= $this->translate('TOUR_TEMPLATE') ?>',
        steps: [
            {
                element: "#system-address",
                placement: "bottom",
                title: "<?= str_replace('"', "'", $this->translate('Mailbox')) ?>",
                content: "<?= str_replace('"', "'", $this->translate('TOUR_MAILBOX_INTRO')) ?>"
            },
            {
                element: "#template-button",
                placement: "right",
                title: "<?= str_replace('"', "'", $this->translate('Mailbox')) ?>",
                content: "<?= str_replace('"', '"', $this->translate('TOUR_MAILBOX_TEMPLATE')) ?>"
            },
        ]
    });

    $(document).ready(function () {
        tour.init().start();
        $('#tour-button')
            .on('click', function () { tour.restart(); })
            .parent().show();
    });
</script>
