<table class="table table-condensed table-hover table-striped">
    <thead>
        <tr>
            <th><?= $this->translate('Preview') ?></th>
            <th><?= $this->translate('Name') ?></th>
            <th><?= $this->translate('Size') ?></th>
        </tr>
    </thead>
    <tbody>
        <?php foreach ($this->attachments as $item): ?>
            <tr>
                <?php if ($item['is_image']): ?>
<?php
    $path = $this->basePath('/admin/mailbox/attachment')
        . '?box=' . urlencode($this->box)
        . '&uid=' . urlencode($this->letter->getUid())
        . '&cid=' . urlencode($item['cid'])
        . '&preview=1';
?>
                    <td><img src="<?= $path ?>"></td>
                <?php else: ?>
                    <td><em><?= $this->translate('No preview available') ?></em></td>
                <?php endif ?>
                <td><?= $this->escapeHtml($item['name']) ?>
                <td><?= $this->escapeHtml($item['size']) ?>
            </tr>
        <?php endforeach ?>
    <tbody>
</table>
