<?php

    $this->layout()->activePage = 'campaign';

?>

<div class="container">
    <div class="row">
        <div class="col-sm-offset-3 col-sm-9">
            <h1><center><span id="page-title"><?= $this->translate('Launch mail campaign') ?></span></center></h1>
        </div>
    </div>

    <div class="row">
        <div class="col-sm-3">
            <div data-sidebar="sm">
                <div class="list-group">
                    <a href="<?= $this->basePath('/admin/campaign/edit?id=' . $this->id) ?>"
                            class="list-group-item active">
                        <h4 class="list-group-item-heading">
                            <?= $this->translate('CAMPAIGN_STEP_1_TITLE') ?>
                        </h4>
                        <p class="list-group-item-text">
                            <?= $this->translate('CAMPAIGN_STEP_1_TEXT') ?>
                        </p>
                    </a>
                    <a href="<?= $this->basePath('/admin/campaign/test?id=' . $this->id) ?>"
                            class="list-group-item">
                        <h4 class="list-group-item-heading">
                            <?= $this->translate('CAMPAIGN_STEP_2_TITLE') ?>
                        </h4>
                        <p class="list-group-item-text">
                            <?= $this->translate('CAMPAIGN_STEP_2_TEXT') ?>
                        </p>
                    </a>
                    <a href="<?= $this->basePath('/admin/campaign/start?id=' . $this->id) ?>"
                            class="list-group-item">
                        <h4 class="list-group-item-heading">
                            <?= $this->translate('CAMPAIGN_STEP_3_TITLE') ?>
                        </h4>
                        <p class="list-group-item-text">
                            <?= $this->translate('CAMPAIGN_STEP_3_TEXT') ?>
                        </p>
                    </a>
                </div>
            </div>
        </div>

        <div class="col-sm-9">
            <?php

                $form = $this->form;

                $security = $form->get('security');
                $name = $form->get('name');
                $whenDeadline = $form->get('when_deadline');
                $groups = $form->get('groups');

            ?>

            <form class="form-horizontal inline-form-offset" name="<?= $form->getName() ?>"
                  method="<?= $form->getAttribute('method') ?>"
                  action="<?= $this->basePath('/admin/campaign/edit?id=' . $this->id) ?>">

                <input type="hidden"
                       name="<?= $security->getName() ?>"
                       value="<?= $security->getValue() ?>">

                <div class="col-sm-offset-2 col-sm-8">
                    <?php foreach (array_merge($this->messages, $security->getMessages()) as $msg): ?>
                        <div class="alert alert-danger">
                            <center><?= $this->escapeHtml($this->translate($msg)) ?></center>
                        </div>
                    <?php endforeach ?>

                    <?php if ($this->saved): ?>
                        <div class="alert alert-success">
                            <center><?= $this->escapeHtml($this->translate('Data saved')) ?></center>
                        </div>
                    <?php endif ?>
                </div>

                <?php $valid = count($name->getMessages()) == 0 ?>
                <div class="form-group <?= $valid ? '' : 'has-error' ?>">
                    <label class="col-sm-4 control-label" for="<?= $name->getName() ?>">
                        <?= $this->escapeHtml($this->translate($name->getLabel())) ?>:
                        <span class="required-marker text-danger">
                            <?= $this->translate('REQUIRED FIELD') ?>
                        </span>
                    </label>
                    <div class="col-sm-6">
                        <input type="text" class="form-control"
                               name="<?= $name->getName() ?>"
                               value="<?= $this->escapeHtml($name->getValue()) ?>"
                               data-on-blur="validateFormField($('form [name=<?= $name->getName() ?>]'))"
                               data-on-enter="$('form [name=<?= $whenDeadline->getName() ?>]').focus()">
                        <div class="help-block">
                            <?php if (!$valid): ?>
                                <ul class="list-unstyled icon-list error-list">
                                <?php foreach ($name->getMessages() as $msg): ?>
                                    <li><?= $this->escapeHtml($this->translate($msg)) ?></li>
                                <?php endforeach ?>
                                </ul>
                            <?php endif ?>
                        </div>
                    </div>
                </div>

                <?php $valid = count($whenDeadline->getMessages()) == 0 ?>
                <div class="form-group <?= $valid ? '' : 'has-error' ?>">
                    <label class="col-sm-4 control-label" for="<?= $whenDeadline->getName() ?>">
                        <?= $this->escapeHtml($this->translate($whenDeadline->getLabel())) ?>:
                    </label>
                    <div class="col-sm-6">
                        <div class="input-group date" id="dt-<?= $whenDeadline->getName() ?>">
                            <input type="text" class="form-control"
                                   name="<?= $whenDeadline->getName() ?>"
                                   value="<?= $this->escapeHtml($whenDeadline->getValue()) ?>"
                                   data-on-blur="validateFormField($('form [name=<?= $whenDeadline->getName() ?>]'))"
                                   data-on-enter="$('form [name=<?= $groups->getName() ?>]').focus()">
                            <span class="input-group-addon">
                                <span class="glyphicon glyphicon-calendar"></span>
                            </span>
                        </div>
                        <div class="help-block">
                            <?php if (!$valid): ?>
                                <ul class="list-unstyled icon-list error-list">
                                <?php foreach ($whenDeadline->getMessages() as $msg): ?>
                                    <li><?= $this->escapeHtml($this->translate($msg)) ?></li>
                                <?php endforeach ?>
                                </ul>
                            <?php endif ?>
                        </div>
                        <script>
                            $('#dt-<?= $whenDeadline->getName() ?>').datetimepicker({
                                format: "YYYY-MM-DD HH:mm:ss Z",
                                locale: '<?= \Locale::getDefault() ?>'
                            });
                        </script>
                    </div>
                </div>

                <?php $valid = count($groups->getMessages()) == 0 ?>
                <div class="form-group <?= $valid ? '' : 'has-error' ?>">
                    <label class="col-sm-4 control-label" for="<?= $groups->getName() ?>">
                        <?= $this->escapeHtml($this->translate($groups->getLabel())) ?>:
                        <span class="required-marker text-danger">
                            <?= $this->translate('REQUIRED FIELD') ?>
                        </span>
                    </label>
                    <div class="col-sm-6">
                        <?php foreach ($groups->getValueOptions() as $value => $label): ?>
                            <div class="checkbox">
                                <label>
                                    <input type="checkbox"
                                           name="<?= $groups->getName() ?>[]"
                                           value="<?= $this->escapeHtml($value) ?>"
                                           <?= in_array($value, $groups->getValue()) ? 'checked="checked"' : '' ?>
                                           data-on-enter="$('#modal-form button[type=submit]').focus().click()">
                                    <?= $this->translate($label) ?>
                                </label>
                            </div>
                        <?php endforeach ?>
                        <div class="help-block">
                            <?php if (!$valid): ?>
                                <ul class="list-unstyled icon-list error-list">
                                <?php foreach ($groups->getMessages() as $msg): ?>
                                    <li><?= $this->escapeHtml($this->translate($msg)) ?></li>
                                <?php endforeach ?>
                                </ul>
                            <?php endif ?>
                        </div>
                    </div>
                </div>

                <div class="form-group">
                    <div class="col-sm-offset-4 col-sm-6">
                        <button type="submit" class="btn btn-primary">
                            <?= $this->translate('Save changes') ?>
                        </button>
                    </div>
                </div>
            </form>

            <script>
                setFormFocus($('form[name="edit-campaign"]'));
            </script>
        </div>
    </div>
</div>
