<?php

    $this->layout()->activePage = 'campaign';

?>
<div class="container">
    <div class="row">
        <div class="col-sm-offset-3 col-sm-9">
            <h1><span id="page-title"><?= $this->translate('Mail campaigns') ?></span></h1>
        </div>
    </div>

    <div class="row">
        <div class="col-sm-3">
            <div data-sidebar="sm">
                <div id="actions-panel" class="panel panel-default">
                    <div class="panel-heading">
                        <h3 class="panel-title"><?= $this->translate('Table actions') ?></h3>
                    </div>
                    <div class="panel-body button-panel">
                        <button id="delete-button" class="btn btn-default disabled" disabled="disabled" onclick="deleteCampaign()">
                            <?= $this->translate('Delete campaign') ?>
                        </button>
                    </div>
                </div>
            </div>
        </div>

        <div class="col-sm-9">
            <div id="table-campaigns"></div>
            <script>
                $('#table-campaigns').dynamicTable({
                    url: '<?= $this->basePath('/admin/campaign/campaign-table') ?>',
                    row_id_column: 'id',
                    sort_column: 'when_created',
                    sort_dir: 'desc',
                    loader_image: '<?= $this->basePath('/img/loader.gif') ?>',
                    strings: dynamicTableStrings,
                    mapper: function (row) {
                        if (row['when_created'] != null) {
                            var m = moment.unix(row['when_created']).local();
                            row['when_created'] = m.format('YYYY-MM-DD HH:mm:ss Z');
                        }
                        if (row['when_started'] != null) {
                            var m = moment.unix(row['when_started']).local();
                            row['when_started'] = m.format('YYYY-MM-DD HH:mm:ss Z');
                        }
                        if (row['when_finished'] != null) {
                            var m = moment.unix(row['when_finished']).local();
                            row['when_finished'] = m.format('YYYY-MM-DD HH:mm:ss Z');
                        }

                        return row;
                    },
                });
                $('#table-campaigns').on('dt.selected', function () {
                    updateActions();
                });
                $('#table-campaigns').on('dt.deselected', function () {
                    updateActions();
                });
            </script>
        <div>
    </div>
</div>

<script>
    function updateActions() {
        var table = $('#table-campaigns').data('dynamicTable');
        var selected = table.getSelected();

        if (selected == 'all' || selected.length) {
            $('#delete-button')
                .removeAttr('disabled')
                .removeClass('disabled');
        } else {
            $('#delete-button')
                .attr('disabled', 'disabled')
                .addClass('disabled');
        }
    }

    function reloadTable() {
        var table = $('#table-campaigns').data('dynamicTable');
        table.refresh();
    }

    function deleteCampaign() {
        var table = $('#table-campaigns').data('dynamicTable');
        var selected = table.getSelected();
        if (selected.length == 0)
            return;

        $.ajax({
            url: '<?= $this->basePath('/admin/campaign/delete-campaign') ?>',
            data: {
                id: selected == 'all' ? '_all' : selected.join(',')
            },
            success: function (html) {
                var modal = $('#modal-form');
                modal.find('.modal-title').text('<?= $this->translate('Delete campaign') ?>');
                modal.find('button[type=submit]').text('<?= $this->translate('Delete') ?>');
                modal.find('.modal-body').html(html);
            }
        });
    }
</script>
