<?php

    $this->layout()->activePage = 'campaign';

?>
<div class="container">
    <div class="row">
        <div class="col-sm-offset-3 col-sm-9">
            <h1><span id="page-title"><?= $this->translate('Mail campaigns') ?></span></h1>
        </div>
    </div>

    <div class="row">
        <div class="col-sm-3">
            <div data-sidebar="sm">
                <div id="status-panel" class="panel panel-default">
                    <div class="panel-heading">
                        <h3 class="panel-title"><?= $this->translate('Status filter') ?></h3>
                    </div>
                    <div class="panel-body button-panel">
                        <?php foreach ($this->statuses as $status): ?>
                            <div class="checkbox">
                                <label>
                                    <input type="checkbox" name="status-<?= $status ?>" value="1" checked="checked">
                                    <?= $this->translate('STATUS_' . strtoupper($status)) ?>
                                </label>
                            </div>
                        <?php endforeach ?>
                        <button class="btn btn-default" onclick="applyFilter()">
                            <?= $this->translate('Apply filter') ?>
                        </button>
                    </div>
                </div>

                <div id="actions-panel" class="panel panel-default">
                    <div class="panel-heading">
                        <h3 class="panel-title"><?= $this->translate('Table actions') ?></h3>
                    </div>
                    <div class="panel-body button-panel">
                        <button id="launch-button" class="btn btn-primary disabled" disabled="disabled" onclick="launchCampaign()">
                            <?= $this->translate('Launch campaign') ?>
                        </button>
                        <hr>
                        <button id="test-button" class="btn btn-default disabled" disabled="disabled" onclick="testCampaign()">
                            <?= $this->translate('Test campaign') ?>
                        </button>
                        <hr>
                        <button id="pause-button" class="btn btn-default disabled" disabled="disabled" onclick="pauseCampaign()">
                            <?= $this->translate('Pause campaign') ?>
                        </button>
                        <hr>
                        <button id="archive-button" class="btn btn-default disabled" disabled="disabled" onclick="archiveCampaign()">
                            <?= $this->translate('Archive campaign') ?>
                        </button>
                        <hr>
                        <button id="delete-button" class="btn btn-default disabled" disabled="disabled" onclick="deleteCampaign()">
                            <?= $this->translate('Delete campaign') ?>
                        </button>
                    </div>
                </div>
            </div>
        </div>

        <div class="col-sm-9">
            <div id="table-campaigns"></div>
            <script>
                $('#table-campaigns').on('dt.selected', function () {
                    updateActions();
                });
                $('#table-campaigns').on('dt.deselected', function () {
                    updateActions();
                });
            </script>
        <div>
    </div>
</div>

<script>
    function applyFilter() {
        var statuses = [
            <?php foreach ($this->statuses as $status): ?>
                '<?= $status ?>=' + ($('.button-panel input[name="status-<?= $status ?>"]').prop('checked') ? 1 : 0),
            <?php endforeach ?>
        ];
        var url = '<?= $this->basePath('/admin/campaign/campaign-table') ?>'
            + '?' + statuses.join('&');

        $('#table-campaigns').dynamicTable({
            url: url,
            row_id_column: 'id',
            sort_column: 'when_created',
            sort_dir: 'desc',
            loader_image: '<?= $this->basePath('/img/loader.gif') ?>',
            strings: dynamicTableStrings,
            mapper: function (row) {
                if (row['when_created'] != null) {
                    var m = moment.unix(row['when_created']).local();
                    row['when_created'] = m.format('<?= $this->translate('GENERIC_MOMENT_FORMAT') ?>');
                }
                if (row['when_started'] != null) {
                    var m = moment.unix(row['when_started']).local();
                    row['when_started'] = m.format('<?= $this->translate('GENERIC_MOMENT_FORMAT') ?>');
                }
                if (row['when_deadline'] != null) {
                    var m = moment.unix(row['when_deadline']).local();
                    row['when_deadline'] = m.format('<?= $this->translate('GENERIC_MOMENT_FORMAT') ?>');
                }
                if (row['when_finished'] != null) {
                    var m = moment.unix(row['when_finished']).local();
                    row['when_finished'] = m.format('<?= $this->translate('GENERIC_MOMENT_FORMAT') ?>');
                }

                return row;
            },
        });
    }
    applyFilter();

    function updateActions() {
        var table = $('#table-campaigns').data('dynamicTable');
        var selected = table.getSelected();

        if (selected != 'all' && selected.length == 1) {
            $('#launch-button')
                .removeAttr('disabled')
                .removeClass('disabled');
            $('#test-button')
                .removeAttr('disabled')
                .removeClass('disabled');
        } else {
            $('#launch-button')
                .attr('disabled', 'disabled')
                .addClass('disabled');
            $('#test-button')
                .attr('disabled', 'disabled')
                .addClass('disabled');
        }

        if (selected == 'all' || selected.length) {
            $('#delete-button')
                .removeAttr('disabled')
                .removeClass('disabled');
            $('#pause-button')
                .removeAttr('disabled')
                .removeClass('disabled');
            $('#archive-button')
                .removeAttr('disabled')
                .removeClass('disabled');
        } else {
            $('#delete-button')
                .attr('disabled', 'disabled')
                .addClass('disabled');
            $('#pause-button')
                .attr('disabled', 'disabled')
                .addClass('disabled');
            $('#archive-button')
                .attr('disabled', 'disabled')
                .addClass('disabled');
        }
    }

    function reloadTables() {
        var table = $('#table-campaigns').data('dynamicTable');
        table.refresh();
    }

    function launchCampaign() {
        var table = $('#table-campaigns').data('dynamicTable');
        var selected = table.getSelected();
        if (selected.length == 0)
            return;

        $.ajax({
            url: '<?= $this->basePath('/admin/campaign/launch-campaign') ?>',
            data: {
                id: selected[0]
            },
            success: function (html) {
                var modal = $('#modal-form');
                modal.find('.modal-title').text('<?= $this->translate('Launch campaign') ?>');
                modal.find('button[type=submit]').text('<?= $this->translate('Launch') ?>').show();
                modal.find('.modal-body').html(html);
            }
        });
    }

    function editCampaign(id) {
        $.ajax({
            url: '<?= $this->basePath('/admin/campaign/edit-campaign') ?>',
            data: {
                id: id
            },
            success: function (html) {
                var modal = $('#modal-form');
                modal.find('.modal-title').text('<?= $this->translate('Edit campaign') ?>');
                modal.find('button[type=submit]').text('<?= $this->translate('Save changes') ?>').show();
                modal.find('.modal-body').html(html);
            }
        });
    }

    function testCampaign() {
        var table = $('#table-campaigns').data('dynamicTable');
        var selected = table.getSelected();
        if (selected.length == 0)
            return;

        $.ajax({
            url: '<?= $this->basePath('/admin/campaign/test-campaign') ?>',
            data: {
                id: selected[0]
            },
            success: function (html) {
                var modal = $('#modal-form');
                modal.find('.modal-title').text('<?= $this->translate('Test campaign') ?>');
                modal.find('button[type=submit]').text('<?= $this->translate('Send test letter') ?>').show();
                modal.find('.modal-body').html(html);
            }
        });
    }

    function pauseCampaign() {
        var table = $('#table-campaigns').data('dynamicTable');
        var selected = table.getSelected();
        if (selected.length == 0)
            return;

        $.ajax({
            url: '<?= $this->basePath('/admin/campaign/pause-campaign') ?>',
            data: {
                id: selected == 'all' ? '_all' : selected.join(',')
            },
            success: function (html) {
                var modal = $('#modal-form');
                modal.find('.modal-title').text('<?= $this->translate('Pause campaign') ?>');
                modal.find('button[type=submit]').text('<?= $this->translate('Pause') ?>').show();
                modal.find('.modal-body').html(html);
            }
        });
    }

    function archiveCampaign() {
        var table = $('#table-campaigns').data('dynamicTable');
        var selected = table.getSelected();
        if (selected.length == 0)
            return;

        $.ajax({
            url: '<?= $this->basePath('/admin/campaign/archive-campaign') ?>',
            data: {
                id: selected == 'all' ? '_all' : selected.join(',')
            },
            success: function (html) {
                var modal = $('#modal-form');
                modal.find('.modal-title').text('<?= $this->translate('Archive campaign') ?>');
                modal.find('button[type=submit]').text('<?= $this->translate('Archive') ?>').show();
                modal.find('.modal-body').html(html);
            }
        });
    }

    function deleteCampaign() {
        var table = $('#table-campaigns').data('dynamicTable');
        var selected = table.getSelected();
        if (selected.length == 0)
            return;

        $.ajax({
            url: '<?= $this->basePath('/admin/campaign/delete-campaign') ?>',
            data: {
                id: selected == 'all' ? '_all' : selected.join(',')
            },
            success: function (html) {
                var modal = $('#modal-form');
                modal.find('.modal-title').text('<?= $this->translate('Delete campaign') ?>');
                modal.find('button[type=submit]').text('<?= $this->translate('Delete') ?>').show();
                modal.find('.modal-body').html(html);
            }
        });
    }

    function statCampaign(id) {
        $.ajax({
            url: '<?= $this->basePath('/admin/campaign/statistics') ?>',
            data: {
                id: id
            },
            success: function (html) {
                var modal = $('#modal-form');
                modal.find('.modal-title').text('<?= $this->translate('Campaign statistics') ?>');
                modal.find('button[type="submit"]').hide();
                modal.find('.modal-body').html(html);
            }
        });
    }

    var tour = new Tour({
        name: 'campaigns',
        template: '<?= $this->translate('TOUR_TEMPLATE') ?>',
        steps: [
            {
                element: "#table-campaigns",
                placement: "left",
                title: "<?= str_replace('"', "'", $this->translate('Campaigns')) ?>",
                content: "<?= str_replace('"', "'", $this->translate('TOUR_CAMPAIGNS_INTRO')) ?>"
            },
        ]
    });

    $(document).ready(function () {
        tour.init().start();
        $('#tour-button')
            .on('click', function () { tour.restart(); })
            .parent().show();
    });
</script>
