<?php

if ($this->script) {    // Run script and return (no form is displayed)
    echo "<script>" . PHP_EOL;
    echo $this->script . PHP_EOL;
    echo "</script>" . PHP_EOL;
    return;
}

$form = $this->form;
$security = $form->get('security');
$id = $form->get('id');

?>

<?php if ($this->noGroups): ?>
    <script>
        bsAlert('<?= $this->translate('CAMPAIGN_NO_GROUPS') ?>');
    </script>
    <?php return ?>
<?php elseif (!$this->readyToStart && !$this->readyToContinue): ?>
    <script>
        bsAlert('<?= $this->translate('CAMPAIGN_ALREADY_LAUNCHED') ?>');
    </script>
    <?php return ?>
<?php else: ?>
    <form class="form-horizontal" name="<?= $form->getName() ?>" onsubmit="return false"
          method="<?= $form->getAttribute('method') ?>"
          action="<?= $this->basePath('/admin/campaign/launch-campaign') ?>">

        <input type="hidden"
               name="<?= $security->getName() ?>"
               value="<?= $security->getValue() ?>">

        <input type="hidden"
               name="<?= $id->getName() ?>"
               value="<?= $id->getValue() ?>">

        <?php foreach (array_merge($this->messages, $security->getMessages()) as $msg): ?>
            <div class="alert alert-danger">
                <center><?= $this->escapeHtml($this->translate($msg)) ?></center>
            </div>
        <?php endforeach ?>

        <p><?= $this->translate('DEMO_MOCK_SENDING') ?></p>

        <?php if (!$this->tested): ?>
            <p><strong><?= $this->translate('ALERT_CAMPAIGN_NOT_TESTED') ?></strong></p>
        <?php endif ?>

        <?php if ($this->readyToContinue): ?>
            <p><?= $this->translate('CONFIRM_CONTINUE_CAMPAIGN') ?></p>
        <?php else: ?>
            <p><?= $this->translate('CONFIRM_START_CAMPAIGN') ?></p>
        <?php endif ?>
    </form>
<?php endif ?>

<script>
    var modal = $('#modal-form');

    initModalForm(modal);                   // See /js/app.js 

    if (!modal.is(':visible'))
        modal.modal('show');

    setFormFocus(modal.find('form'));       // See /js/app.js
</script>
