<?php

    $this->layout()->activePage = 'campaign';

?>

<div class="container">
    <div class="row">
        <div class="col-sm-offset-3 col-sm-9">
            <h1><center><span id="page-title"><?= $this->translate('Launch mail campaign') ?></span></center></h1>
        </div>
    </div>

    <div class="row">
        <div class="col-sm-3">
            <div data-sidebar="sm">
                <div class="list-group">
                    <a href="<?= $this->basePath('/admin/campaign/edit?id=' . $this->id) ?>"
                            class="list-group-item">
                        <h4 class="list-group-item-heading">
                            <?= $this->translate('CAMPAIGN_STEP_1_TITLE') ?>
                        </h4>
                        <p class="list-group-item-text">
                            <?= $this->translate('CAMPAIGN_STEP_1_TEXT') ?>
                        </p>
                    </a>
                    <a href="<?= $this->basePath('/admin/campaign/test?id=' . $this->id) ?>"
                            class="list-group-item active">
                        <h4 class="list-group-item-heading">
                            <?= $this->translate('CAMPAIGN_STEP_2_TITLE') ?>
                        </h4>
                        <p class="list-group-item-text">
                            <?= $this->translate('CAMPAIGN_STEP_2_TEXT') ?>
                        </p>
                    </a>
                    <a href="<?= $this->basePath('/admin/campaign/start?id=' . $this->id) ?>"
                            class="list-group-item">
                        <h4 class="list-group-item-heading">
                            <?= $this->translate('CAMPAIGN_STEP_3_TITLE') ?>
                        </h4>
                        <p class="list-group-item-text">
                            <?= $this->translate('CAMPAIGN_STEP_3_TEXT') ?>
                        </p>
                    </a>
                </div>
            </div>
        </div>

        <div class="col-sm-9">
            <?php if (count($this->testers) == 0): ?>
                <div class="col-sm-offset-2 col-sm-8">
                    <div class="alert alert-danger">
                        <center><?= $this->translate('TEST_CAMPAIGN_NO_TESTERS') ?></center>
                    </div>
                </div>
            <?php endif ?>
        </div>
    </div>
</div>
