<?= $this->doctype(); ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?= $this->headTitle($this->translate('APP_TITLE'))
                 ->setSeparator(' - ')
                 ->setAutoEscape(false) ?>

<?= $this->headMeta()
         ->appendName('viewport', 'width=device-width, initial-scale=1.0')
         ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
         ->toString(8) ?>

<?php if (@$_ENV['ENVIRONMENT'] == 'development'): ?>

    <?= $this->headLink([
                    'rel' => 'shortcut icon',
                    'type' => 'image/vnd.microsoft.icon',
                    'href' => $this->basePath('/img/favicon.ico')
               ])
             ->prependStylesheet($this->basePath('/css/app.css'))
             ->prependStylesheet($this->basePath('/css/vendor.css'))
             ->toString(8) ?>
     
    <?= $this->headScript()
             ->prependFile($this->basePath('/js/app.js'))
             ->prependFile($this->basePath('/js/vendor.js'))
             ->toString(8) ?>

<?php else: // Production ?>

    <?= $this->headLink([
                    'rel' => 'shortcut icon',
                    'type' => 'image/vnd.microsoft.icon',
                    'href' => $this->basePath('/img/favicon.ico')
               ])
             ->prependStylesheet($this->basePath('/css/app.min.css'))
             ->prependStylesheet($this->basePath('/css/vendor.min.css'))
             ->toString(8) ?>
     
    <?= $this->headScript()
             ->prependFile($this->basePath('/js/app.min.js'))
             ->prependFile($this->basePath('/js/vendor.min.js'))
             ->toString(8) ?>

<?php endif ?>

        <script>
            var dynamicTableStrings = {
                DT_BANNER_LOADING: '<?= $this->translate('DT_BANNER_LOADING') ?>',
                DT_BANNER_EMPTY: '<?= $this->translate('DT_BANNER_EMPTY') ?>',
                DT_BUTTON_PAGE_SIZE: '<?= $this->translate('DT_BUTTON_PAGE_SIZE') ?>',
                DT_BUTTON_COLUMNS: '<?= $this->translate('DT_BUTTON_COLUMNS') ?>',
                DT_BUTTON_REFRESH: '<?= $this->translate('DT_BUTTON_REFRESH') ?>',
                DT_BUTTON_OK: '<?= $this->translate('DT_BUTTON_OK') ?>',
                DT_BUTTON_CLEAR: '<?= $this->translate('DT_BUTTON_CLEAR') ?>',
                DT_BUTTON_CANCEL: '<?= $this->translate('DT_BUTTON_CANCEL') ?>',
                DT_TITLE_FILTER_WINDOW: '<?= $this->translate('DT_TITLE_FILTER_WINDOW') ?>',
                DT_LABEL_CURRENT_PAGE: '<?= $this->translate('DT_LABEL_CURRENT_PAGE') ?>',
                DT_LABEL_ALL_PAGES: '<?= $this->translate('DT_LABEL_ALL_PAGES') ?>',
                DT_LABEL_PAGE_OF_1: '<?= $this->translate('DT_LABEL_PAGE_OF_1') ?>',
                DT_LABEL_PAGE_OF_2: '<?= $this->translate('DT_LABEL_PAGE_OF_2') ?>',
                DT_LABEL_FILTER_LIKE: '<?= $this->translate('DT_LABEL_FILTER_LIKE') ?>',
                DT_LABEL_FILTER_EQUAL: '<?= $this->translate('DT_LABEL_FILTER_EQUAL') ?>',
                DT_LABEL_FILTER_BETWEEN_START: '<?= $this->translate('DT_LABEL_FILTER_BETWEEN_START') ?>',
                DT_LABEL_FILTER_BETWEEN_END: '<?= $this->translate('DT_LABEL_FILTER_BETWEEN_END') ?>',
                DT_LABEL_FILTER_NULL: '<?= $this->translate('DT_LABEL_FILTER_NULL') ?>',
                DT_LABEL_TRUE: '<?= $this->translate('DT_LABEL_TRUE') ?>',
                DT_LABEL_FALSE: '<?= $this->translate('DT_LABEL_FALSE') ?>',
                DT_DATE_TIME_FORMAT: '<?= $this->translate('DT_DATE_TIME_FORMAT') ?>',
            };
        </script>
    </head>
    <body class="extra-padding">

        <nav class="navbar navbar-default navbar-fixed-top">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#layout-navbar-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="<?= $this->basePath('/admin') ?>">
                        <?= $this->translate('APP_TITLE') ?>
                    </a>
                </div>

                <div class="collapse navbar-collapse" id="layout-navbar-collapse">
                    <ul class="nav navbar-nav">
                        <li class="dropdown <?= in_array($activePage, [ 'parser', 'mailbox', 'outgoing' ]) ? 'active' : '' ?>">
                            <a id="mailbox-navbar" href="javascript:void(0)" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
                                <?= $this->translate('Mail') ?>
                                <span class="caret"></span>
                            </a>
                            <ul class="dropdown-menu" role="menu">
                                <li>
                                    <a href="<?= $this->basePath('/admin/parser') ?>">
                                        <?= $this->translate('Message parser') ?>
                                    </a>
                                </li>
                                <li>
                                    <a href="<?= $this->basePath('/admin/mailbox') ?>">
                                        <?= $this->translate('Mailbox') ?>
                                    </a>
                                </li>
                                <li>
                                    <a href="<?= $this->basePath('/admin/outgoing') ?>">
                                        <?= $this->translate('Outgoing messages') ?>
                                    </a>
                                </li>
                            </ul>
                        </li>

                        <li class="dropdown <?= in_array($activePage, [ 'client', 'group', 'campaign' ]) ? 'active' : '' ?>">
                            <a href="javascript:void(0)" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
                                <?= $this->translate('Campaign') ?>
                                <span class="caret"></span>
                            </a>
                            <ul class="dropdown-menu" role="menu">
                                <li>
                                    <a href="<?= $this->basePath('/admin/group') ?>">
                                        <?= $this->translate('Client groups') ?>
                                    </a>
                                </li>
                                <li>
                                    <a href="<?= $this->basePath('/admin/client') ?>">
                                        <?= $this->translate('Clients') ?>
                                    </a>
                                </li>
                                <li>
                                    <a href="<?= $this->basePath('/admin/campaign') ?>">
                                        <?= $this->translate('Mail campaigns') ?>
                                    </a>
                                </li>
                            </ul>
                        </li>

                        <li <?= $activePage == 'document' ? 'class="active"' : '' ?>>
                            <a href="<?= $this->basePath('/admin/document') ?>">
                                <?= $this->translate('Data forms') ?>
                            </a>
                        </li>

                        <li <?= $activePage == 'syslog' ? 'class="active"' : '' ?>>
                            <a href="<?= $this->basePath('/admin/syslog') ?>">
                                <?= $this->translate('System log') ?>
                            </a>
                        </li>

                        <li class="dropdown">
                            <a href="javascript:void(0)" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
                                <?= $this->translate('Settings') ?>
                                <span class="caret"></span>
                            </a>
                            <ul class="dropdown-menu" role="menu">
                                <li>
                                    <a href="javascript:void(0)" onclick="settingsForm('mailbox')">
                                        <?= $this->translate('Mailbox') ?>
                                    </a>
                                </li>
                            </ul>
                        </li>
                    </ul>

                    <div class="nav navbar-nav navbar-right" style="display: none">
                        <button id="tour-button" class="navbar-btn btn btn-default">
                            <?= $this->translate('Tutorial') ?>
                        </button>
                    </div>

                    <ul class="nav navbar-nav navbar-right">
                        <li class="dropdown">
                            <a href="javascript:void(0)" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
                                <?php $short = substr($this->locale['current'], 0, 2); ?>
                                <img src="<?= $this->basePath('/img/flags/' . $short . '.gif') ?>">
                                <?= $short ?>
                                <span class="caret"></span>
                            </a>
                            <ul class="dropdown-menu" role="menu">
                                <?php foreach ($this->locale['available'] as $locale): ?>
                                    <li>
                                        <a href="javascript:void(0)" onclick="$.cookie('locale', '<?= $locale ?>', { path: '/' }); window.location.reload()">
                                            <span class="glyphicon glyphicon-ok <?= $this->locale['cookie'] == $locale ?: 'invisible' ?>"></span>
                                            <?= $this->translate($locale) ?>
                                        </a>
                                    </li>
                                <?php endforeach ?>
                                <li class="divider"></li>
                                <li>
                                    <a href="javascript:void(0)" onclick="$.removeCookie('locale', { path: '/' }); window.location.reload()">
                                        <span class="glyphicon glyphicon-ok <?= $this->locale['cookie'] == '' ?: 'invisible' ?>"></span>
                                        <?= $this->translate('Autodetect') ?>
                                    </a>
                                </li>
                            </ul>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>

<?= $this->content; ?>

<?= $this->inlineScript() ?>

        <div id="modal-form" class="modal">
            <div class="modal-dialog">
                <div class="modal-content">
                    <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal">&times;</button>
                        <h4 class="modal-title"></h4>
                    </div>
                    <div class="modal-body">
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-default" data-dismiss="modal">
                            <?= $this->translate('Cancel') ?>
                        </button>
                        <button type="submit" class="btn btn-primary">
                            <?= $this->translate('Submit') ?>
                        </button>
                    </div>
                </div>
            </div>
        </div>

        <script>
            function settingsForm(page) {
                var title = null, submit = null;
                switch (page) {
                    case 'mailbox':
                        title = '<?= $this->translate('Mailbox settings') ?>';
                        submit = '<?= $this->translate('Save') ?>';
                        break;
                }

                $.ajax({
                    url: '<?= $this->basePath('/admin/setting/') ?>' + page + '-form',
                    success: function (html) {
                        var modal = $('#modal-form');
                        modal.find('.modal-title').text(title);
                        modal.find('button[type=submit]').text(submit);
                        modal.find('.modal-body').html(html);
                    }
                });
            }
        </script>

        <div id="letter-modal" class="modal">
            <div class="modal-dialog modal-lg">
                <div class="modal-content">
                    <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal">
                            <span aria-hidden="true">&times;</span>
                            <span class="sr-only"><?= $this->translate('Close') ?></span>
                        </button>
                        <h4 class="modal-title"></h4>
                    </div>
                    <div class="modal-body">
                        <div role="tabpanel">
                            <ul class="nav nav-tabs" role="tablist">
                                <li role="presentation" class="active">
                                    <a href="#html" aria-controls="html" role="tab" data-toggle="tab">
                                        <?= $this->translate('HTML') ?>
                                    </a>
                                </li>
                                <li role="presentation">
                                    <a href="#text" aria-controls="text" role="tab" data-toggle="tab">
                                        <?= $this->translate('Text') ?>
                                    </a>
                                </li>
                                <li role="presentation">
                                    <a href="#attachments" aria-controls="attachments" role="tab" data-toggle="tab">
                                        <?= $this->translate('Attachments') ?>
                                    </a>
                                </li>
                                <li role="presentation">
                                    <a href="#log" aria-controls="log" role="tab" data-toggle="tab">
                                        <?= $this->translate('Analysis log') ?>
                                    </a>
                                </li>
                                <li role="presentation">
                                    <a href="#source" aria-controls="source" role="tab" data-toggle="tab">
                                        <?= $this->translate('Source') ?>
                                    </a>
                                </li>
                            </ul>
                            <div class="tab-content">
                                <div id="html" role="tabpanel" class="tab-pane active">
                                    <div class="tab-pane-loader"></div>
                                    <iframe class="letter-frame"></iframe>
                                </div>
                                <div id="text" role="tabpanel" class="tab-pane">
                                    <div class="tab-pane-loader"></div>
                                    <div class="letter-frame"></div>
                                </div>
                                <div id="attachments" role="tabpanel" class="tab-pane">
                                    <div class="tab-pane-loader"></div>
                                    <div class="letter-frame"></div>
                                </div>
                                <div id="log" role="tabpanel" class="tab-pane">
                                    <div class="tab-pane-loader"></div>
                                    <div class="letter-frame"></div>
                                </div>
                                <div id="source" role="tabpanel" class="tab-pane">
                                    <div class="tab-pane-loader"></div>
                                    <div class="letter-frame"></div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="modal-footer">
                        <div class="pull-left">
                            <strong>
                                <?= $this->translate('Letter check status') ?>:
                                <span id="parse-status"><?= $this->translate('Loading...') ?></span>
                            </strong>
                        </div>
                        <button class="btn btn-primary" data-dismiss="modal">
                            <?= $this->translate('Close') ?>
                        </button>
                    </div>
                </div>
            </div>
        </div>

        <script>
            function openLetter(data) {
                $('#letter-modal .modal-title').text('<?= $this->translate('Loading...') ?>');
                $('#letter-modal .letter-frame').hide();
                $('#letter-modal .tab-pane-loader').show();

                $('#letter-modal').modal('show');

                $.getJSON(
                    '<?= $this->basePath('/admin/letter/show-letter') ?>',
                    data,
                    function (data) {
                        var iframeContext = $('#html iframe')[0].contentWindow.document;
                        $('html', iframeContext).html(data.html);
                        $('#text .letter-frame').html(data.text);
                        $('#attachments .letter-frame').html(data.attachments);
                        $('#log .letter-frame').html(data.log);
                        $('#source .letter-frame').html(data.source);

                        $('#letter-modal .modal-title').html(data.subject);
                        if (data.error === false)
                            $('#parse-status').html('<span class="text-success"><?= $this->translate('Success') ?></span>');
                        else if (data.error == 'analysis')
                            $('#parse-status').html('<span class="text-danger"><?= $this->translate('Analysis error') ?></span>');
                        else if (data.error == 'syntax')
                            $('#parse-status').html('<span class="text-danger"><?= $this->translate('Syntax error') ?></span>');
                        $('#letter-modal .tab-pane-loader').hide();
                        $('#letter-modal .letter-frame').show();
                    }
                );
            }
        </script>

    </body>
</html>
