<?php

if ($this->script) {    // Run script and return (no form is displayed)
    echo "<script>" . PHP_EOL;
    echo $this->script . PHP_EOL;
    echo "</script>" . PHP_EOL;
    return;
}

$form = $this->form;

$security = $form->get('security');
$id = $form->has('id') ? $form->get('id') : null;
$name = $form->get('name');

?>

<form class="form-horizontal" name="<?= $form->getName() ?>" onsubmit="return false"
      method="<?= $form->getAttribute('method') ?>"
      action="<?= $this->basePath('/admin/group/edit-group') ?>">

    <input type="hidden"
           name="<?= $security->getName() ?>"
           value="<?= $security->getValue() ?>">

    <?php if ($id): ?>
        <input type="hidden"
               name="<?= $id->getName() ?>"
               value="<?= $id->getValue() ?>">
    <?php endif ?>

    <?php foreach (array_merge($this->messages, $security->getMessages()) as $msg): ?>
        <div class="alert alert-danger">
            <center><?= $this->escapeHtml($this->translate($msg)) ?></center>
        </div>
    <?php endforeach ?>

    <?php $valid = count($name->getMessages()) == 0 ?>
    <div class="form-group <?= $valid ? '' : 'has-error' ?>">
        <label class="col-sm-4 control-label" for="<?= $name->getName() ?>">
            <?= $this->escapeHtml($this->translate($name->getLabel())) ?>:
            <span class="required-marker text-danger">
                <?= $this->translate('REQUIRED FIELD') ?>
            </span>
        </label>
        <div class="col-sm-8">
            <input type="text" class="form-control"
                   name="<?= $name->getName() ?>"
                   value="<?= $this->escapeHtml($name->getValue()) ?>"
                   data-on-blur="validateFormField($('#modal-form [name=<?= $name->getName() ?>]'))"
                   data-on-enter="$('#modal-form button[type=submit]').focus().click()">
            <div class="help-block">
                <?php if (!$valid): ?>
                    <ul class="list-unstyled icon-list error-list">
                    <?php foreach ($name->getMessages() as $msg): ?>
                        <li><?= $this->escapeHtml($this->translate($msg)) ?></li>
                    <?php endforeach ?>
                    </ul>
                <?php endif ?>
            </div>
        </div>
    </div>
</form>

<script>
    var modal = $('#modal-form');

    initModalForm(modal);                   // See /js/app.js 

    if (!modal.is(':visible'))
        modal.modal('show');

    setFormFocus(modal.find('form'));       // See /js/app.js
</script>
