<?php

    $this->layout()->activePage = 'sent-log';

?>
<div class="container">
    <div class="row">
        <div class="col-sm-12">
            <h1><span id="page-title"><?= $this->translate('Sent log') ?></span></h1>
        </div>
    </div>

    <div class="row">
        <div class="col-sm-12">
            <div id="table-sent"></div>
            <script>
                $('#table-sent').dynamicTable({
                    url: '<?= $this->basePath('/admin/sent-log/sent-table') ?>',
                    row_id_column: 'id',
                    sort_column: 'when_sent',
                    sort_dir: 'desc',
                    loader_image: '<?= $this->basePath('/img/loader.gif') ?>',
                    strings: dynamicTableStrings,
                    mapper: function (row) {
                        if (row['when_sent'] != null) {
                            var m = moment.unix(row['when_sent']).local();
                            row['when_sent'] = m.format('<?= $this->translate('GENERIC_MOMENT_FORMAT') ?>');
                        }

                        return row;
                    },
                });
            </script>
        <div>
    </div>
</div>
