<?php

if ($this->script) {    // Run script and return (no form is displayed)
    echo "<script>" . PHP_EOL;
    echo $this->script . PHP_EOL;
    echo "</script>" . PHP_EOL;
    return;
}

$form = $this->form;

$security = $form->get('security');
$id = $form->has('id') ? $form->get('id') : null;
$email = $form->get('email');
$whenBounced = $form->get('when_bounced');
$groups = $form->get('groups');

?>

<form class="form-horizontal" name="<?= $form->getName() ?>" onsubmit="return false"
      method="<?= $form->getAttribute('method') ?>"
      action="<?= $this->basePath('/admin/client/edit-client') ?>">

    <input type="hidden"
           name="<?= $security->getName() ?>"
           value="<?= $security->getValue() ?>">

    <?php if ($id): ?>
        <input type="hidden"
               name="<?= $id->getName() ?>"
               value="<?= $id->getValue() ?>">
    <?php endif ?>

    <?php foreach (array_merge($this->messages, $security->getMessages()) as $msg): ?>
        <div class="alert alert-danger">
            <center><?= $this->escapeHtml($this->translate($msg)) ?></center>
        </div>
    <?php endforeach ?>

    <?php $valid = count($email->getMessages()) == 0 ?>
    <div class="form-group <?= $valid ? '' : 'has-error' ?>">
        <label class="col-sm-4 control-label" for="<?= $email->getName() ?>">
            <?= $this->escapeHtml($this->translate($email->getLabel())) ?>:
            <span class="required-marker text-danger">
                <?= $this->translate('REQUIRED FIELD') ?>
            </span>
        </label>
        <div class="col-sm-8">
            <input type="text" class="form-control"
                   name="<?= $email->getName() ?>"
                   value="<?= $this->escapeHtml($email->getValue()) ?>"
                   data-on-blur="validateFormField($('#modal-form [name=<?= $email->getName() ?>]'))"
                   data-on-enter="$('#modal-form [name=<?= $whenBounced->getName() ?>]').focus()">
            <div class="help-block">
                <?php if (!$valid): ?>
                    <ul class="list-unstyled icon-list error-list">
                    <?php foreach ($email->getMessages() as $msg): ?>
                        <li><?= $this->escapeHtml($this->translate($msg)) ?></li>
                    <?php endforeach ?>
                    </ul>
                <?php endif ?>
            </div>
        </div>
    </div>

    <?php $valid = count($whenBounced->getMessages()) == 0 ?>
    <div class="form-group <?= $valid ? '' : 'has-error' ?>">
        <label class="col-sm-4 control-label" for="<?= $whenBounced->getName() ?>">
            <?= $this->escapeHtml($this->translate($whenBounced->getLabel())) ?>:
        </label>
        <div class="col-sm-8">
            <div class="input-group date" id="dt-<?= $whenBounced->getName() ?>">
                <input type="text" class="form-control"
                       name="<?= $whenBounced->getName() ?>"
                       value="<?= $this->escapeHtml($whenBounced->getValue()) ?>"
                       data-on-blur="validateFormField($('#modal-form [name=<?= $whenBounced->getName() ?>]'))"
                       data-on-enter="$('#modal-form [name=<?= $groups->getName() ?>]').focus()">
                <span class="input-group-addon">
                    <span class="glyphicon glyphicon-calendar"></span>
                </span>
            </div>
            <div class="help-block">
                <?php if (!$valid): ?>
                    <ul class="list-unstyled icon-list error-list">
                    <?php foreach ($whenBounced->getMessages() as $msg): ?>
                        <li><?= $this->escapeHtml($this->translate($msg)) ?></li>
                    <?php endforeach ?>
                    </ul>
                <?php endif ?>
            </div>
            <script>
                $('#dt-<?= $whenBounced->getName() ?>').datetimepicker({
                    format: "YYYY-MM-DD HH:mm:ss Z",
                    locale: '<?= \Locale::getDefault() ?>'
                });
            </script>
        </div>
    </div>

    <?php $valid = count($groups->getMessages()) == 0 ?>
    <div class="form-group <?= $valid ? '' : 'has-error' ?>">
        <label class="col-sm-4 control-label" for="<?= $groups->getName() ?>">
            <?= $this->escapeHtml($this->translate($groups->getLabel())) ?>:
        </label>
        <div class="col-sm-8">
            <?php foreach ($groups->getValueOptions() as $value => $label): ?>
                <div class="checkbox">
                    <label>
                        <input type="checkbox"
                               name="<?= $groups->getName() ?>[]"
                               value="<?= $this->escapeHtml($value) ?>"
                               <?= in_array($value, $groups->getValue()) ? 'checked="checked"' : '' ?>
                               data-on-enter="$('#modal-form button[type=submit]').focus().click()">
                        <?= $this->translate($label) ?>
                    </label>
                </div>
            <?php endforeach ?>
            <div class="help-block">
                <?php if (!$valid): ?>
                    <ul class="list-unstyled icon-list error-list">
                    <?php foreach ($groups->getMessages() as $msg): ?>
                        <li><?= $this->escapeHtml($this->translate($msg)) ?></li>
                    <?php endforeach ?>
                    </ul>
                <?php endif ?>
            </div>
        </div>
    </div>
</form>

<script>
    var modal = $('#modal-form');

    initModalForm(modal);                   // See /js/app.js 

    if (!modal.is(':visible'))
        modal.modal('show');

    setFormFocus(modal.find('form'));       // See /js/app.js
</script>
