<table class="table table-condensed table-hover table-striped">
    <thead>
        <tr>
            <th><?= $this->translate('Preview') ?></th>
            <th><?= $this->translate('Name') ?></th>
            <th><?= $this->translate('Type') ?></th>
            <th><?= $this->translate('Size') ?></th>
        </tr>
    </thead>
    <tbody>
        <?php foreach ($this->attachments as $item): ?>
            <tr>
                <?php if ($item['is_image']): ?>
<?php
    if (isset($params['box']))
        $query = 'box=' . urlencode($params['box']) . '&uid=' . urlencode($letter->getUid());
    else if (isset($params['template']))
        $query = 'template=' . urlencode($params['template']);
    else if (isset($params['letter']))
        $query = 'letter=' . urlencode($params['letter']);

    $path = $this->basePath('/admin/letter/attachment')
        . '?' . $query
        . '&cid=' . urlencode($item['cid'])
        . '&filename=' . urlencode($item['name'])
        . '&preview=1';
?>
                    <td><img src="<?= $path ?>"></td>
                <?php else: ?>
                    <td><em><?= $this->translate('No preview available') ?></em></td>
                <?php endif ?>
                <td><?= $this->escapeHtml($item['name']) ?>
                <td><?= $this->escapeHtml($item['type']) ?>
                <td><?= $this->escapeHtml($item['size']) ?>
            </tr>
        <?php endforeach ?>
    <tbody>
</table>
