<?php

if ($this->script) {    // Run script and return (no form is displayed)
    echo "<script>" . PHP_EOL;
    echo $this->script . PHP_EOL;
    echo "</script>" . PHP_EOL;
    return;
}

$form = $this->form;
$security = $form->get('security');
$interval = $form->get('interval');

?>

<form class="form-horizontal" name="<?= $form->getName() ?>" onsubmit="return false"
      method="<?= $form->getAttribute('method') ?>"
      action="<?= $this->basePath('/admin/setting/email-sender-form') ?>">

    <input type="hidden"
           name="<?= $security->getName() ?>"
           value="<?= $security->getValue() ?>">

    <?php foreach (array_merge($this->messages, $security->getMessages()) as $msg): ?>
        <div class="alert alert-danger">
            <center><?= $this->escapeHtml($this->translate($msg)) ?></center>
        </div>
    <?php endforeach ?>

    <?php $valid = count($interval->getMessages()) == 0 ?>
    <div class="form-group <?= $valid ?: 'has-error' ?>">
            <label class="col-sm-4 control-label"
                   for="<?= $interval->getName() ?>">
            <?= $this->escapeHtml($this->translate($interval->getLabel())) ?>:
        </label>
        <div class="col-sm-8">
            <div class="input-group">
                <span class="input-group-addon"><?= $this->translate('Seconds') ?>:</span>
                <input class="form-control" type="text"
                       name="<?= $interval->getName() ?>"
                       value="<?= $this->escapeHtml($interval->getValue()) ?>"
                       data-on-blur="validateFormField($('input[name=<?= $interval->getName() ?>]'))"
                       data-on-enter="$('#modal-form button[type=submit]').click()">
            </div>
            <div class="help-block">
                <?php if (!$valid): ?>
                    <ul class="list-unstyled icon-list error-list">
                    <?php foreach ($interval->getMessages() as $msg): ?>
                        <li><?= $this->escapeHtml($msg) ?></li>
                    <?php endforeach ?>
                    </ul>
                <?php endif ?>
            </div>
        </div>
    </div>
</form>

<script>
    var modal = $('#modal-form');

    initModalForm(modal);                   // See /js/app.js 

    if (!modal.is(':visible'))
        modal.modal('show');

    setFormFocus(modal.find('form'));       // See /js/app.js
</script>
