<?php

    $this->layout('layout/form');

    $form = $this->form;
    $form->prepare();

    $security = $form->get('security');
    $login = $form->get('login');
    $password = $form->get('password');
    $submit = $form->get('submit');

?>

<div class="centered-wrapper">
    <div class="centered">
        <div class="popover login-popover">
            <h3 class="popover-title">
                <?= $this->translate('Restricted area') ?>
            </h3>
            <div class="popover-content">
                <form role="form" class="form-horizontal"
                      method="<?= $form->getAttribute('method') ?>">
                    <input type="hidden"
                           name="<?= $security->getName() ?>"
                           value="<?= $security->getValue() ?>">
                    <?php foreach (array_merge($this->messages, $security->getMessages()) as $msg): ?>
                        <div class="alert alert-danger">
                            <?= $this->escapeHtml($this->translate($msg)) ?>
                        </div>
                    <?php endforeach ?>

                    <?php $valid = count($login->getMessages()) == 0 ?>
                    <div class="form-group <?= $valid ?: 'has-error' ?>">
                            <label class="col-sm-4 control-label"
                                   for="<?= $login->getName() ?>">
                            <?= $this->escapeHtml($this->translate($login->getLabel())) ?>:
                        </label>
                        <div class="col-sm-8">
                            <input class="form-control" type="text"
                                   name="<?= $login->getName() ?>"
                                   value="<?= $this->escapeHtml($login->getValue()) ?>"
                                   data-on-blur="validateFormField($('input[name=<?= $login->getName() ?>]'))"
                                   data-on-enter="$('input[name=<?= $password->getName() ?>]').focus()">
                            <div class="help-block">
                                <?php if (!$valid): ?>
                                    <ul class="list-unstyled icon-list error-list">
                                    <?php foreach ($login->getMessages() as $msg): ?>
                                        <li><?= $this->escapeHtml($this->translate($msg)) ?></li>
                                    <?php endforeach ?>
                                    </ul>
                                <?php endif ?>
                            </div>
                        </div>
                    </div>

                    <?php $valid = count($password->getMessages()) == 0 ?>
                    <div class="form-group <?= $valid ?: 'has-error' ?>">
                        <label class="col-sm-4 control-label"
                               for="<?= $password->getName() ?>">
                            <?= $this->escapeHtml($this->translate($password->getLabel())) ?>:
                        </label>
                        <div class="col-sm-8">
                            <input class="form-control" type="password"
                                   name="<?= $password->getName() ?>"
                                   data-on-blur="validateFormField($('input[name=<?= $password->getName() ?>]'))"
                                   data-on-enter="$('form').submit()">
                            <div class="help-block">
                                <?php if (!$valid): ?>
                                    <ul class="list-unstyled icon-list error-list">
                                    <?php foreach ($password->getMessages() as $msg): ?>
                                        <li><?= $this->escapeHtml($this->translate($msg)) ?></li>
                                    <?php endforeach ?>
                                    </ul>
                                <?php endif ?>
                            </div>
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="col-sm-offset-4 col-sm-8">
                            <button class="btn btn-default" type="submit">
                                <?= $this->escapeHtml($this->translate($submit->getLabel())) ?>
                            </button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
<script>
    $(document).ready(function () {
        var errors = $('form .form-group.has-error input');
        var all = $('form .form-group input:not(.disabled)');
        if (errors.length > 0)
            errors[0].focus();
        else if (all.length > 0)
            all[0].focus();
    });
</script>
