<?php

    $this->layout()->activePage = 'outgoing';

?>
<div class="container">
    <div class="row">
        <div class="col-sm-offset-3 col-sm-9">
            <h1><span id="page-title"><?= $this->translate('Outgoing messages') ?></span></h1>
        </div>
    </div>

    <div class="row">
        <div class="col-sm-3">
            <div data-sidebar="sm">
                <div id="status-panel" class="panel panel-default">
                    <div class="panel-heading">
                        <h3 class="panel-title"><?= $this->translate('Outgoing filter') ?></h3>
                    </div>
                    <div class="panel-body button-panel">
                        <?php foreach ($this->statuses as $status): ?>
                            <div class="checkbox">
                                <label>
                                    <input type="checkbox" name="status-<?= $status ?>" value="1" checked="checked">
                                    <?= $this->translate('STATUS_' . strtoupper($status)) ?>
                                </label>
                            </div>
                        <?php endforeach ?>
                        <button class="btn btn-default" onclick="applyFilter()">
                            <?= $this->translate('Apply filter') ?>
                        </button>
                    </div>
                </div>
            </div>
        </div>

        <div class="col-sm-9">
            <div id="table-outgoing"></div>
        <div>
    </div>
</div>

<script>
    function applyFilter() {
        var statuses = [
            <?php foreach ($this->statuses as $status): ?>
                '<?= $status ?>=' + ($('.button-panel input[name="status-<?= $status ?>"]').prop('checked') ? 1 : 0),
            <?php endforeach ?>
        ];
        var url = '<?= $this->basePath('/admin/outgoing/outgoing-table') ?>'
            + '?' + statuses.join('&');

        $('#table-outgoing').dynamicTable({
            url: url,
            row_id_column: 'id',
            sort_column: 'id',
            sort_dir: 'desc',
            loader_image: '<?= $this->basePath('/img/loader.gif') ?>',
            strings: dynamicTableStrings,
            mapper: function (row) {
                if (row['when_created'] != null) {
                    var m = moment.unix(row['when_created']).local();
                    row['when_created'] = m.format('<?= $this->translate('GENERIC_MOMENT_FORMAT') ?>');
                }
                if (row['when_processed'] != null) {
                    var m = moment.unix(row['when_processed']).local();
                    row['when_processed'] = m.format('<?= $this->translate('GENERIC_MOMENT_FORMAT') ?>');
                }

                return row;
            },
        });
    }

    function reloadTables() {
        var table = $('#table-outgoing').data('dynamicTable');
        table.refresh();
    }

    var tour = new Tour({
        name: 'outgoing',
        template: '<?= $this->translate('TOUR_TEMPLATE') ?>',
        steps: [
            {
                element: "#table-outgoing",
                placement: "left",
                title: "<?= str_replace('"', "'", $this->translate('Outgoing')) ?>",
                content: "<?= str_replace('"', "'", $this->translate('TOUR_OUTGOING_INTRO')) ?>"
            },
        ],
    });

    $(document).ready(function () {
        applyFilter();
        tour.init().start();
        $('#tour-button')
            .on('click', function () { tour.restart(); })
            .parent().show();
    });
</script>
