<?php

    $this->layout()->activePage = 'outgoing';

?>
<div class="container">
    <div class="row">
        <div class="col-sm-offset-3 col-sm-9">
            <h1><span id="page-title"><?= $this->translate('Outgoing messages') ?></span></h1>
        </div>
    </div>

    <div class="row">
        <div class="col-sm-3">
            <div data-sidebar="sm">
                <div id="status-panel" class="panel panel-default">
                    <div class="panel-heading">
                        <h3 class="panel-title"><?= $this->translate('Outgoing filter') ?></h3>
                    </div>
                    <div class="panel-body button-panel">
                        <div class="radio">
                            <label>
                                <input type="radio" name="status" value="planned"
                                       onclick="$(this).closest('.button-panel').find('.checkbox').hide()">
                                <?= $this->translate('OUTGOING_PLANNED_FILTER') ?>
                            </label>
                        </div>
                        <div class="radio">
                            <label>
                                <input type="radio" name="status" value="processed" checked="checked"
                                       onclick="$(this).closest('.button-panel').find('.checkbox').show()">
                                <?= $this->translate('OUTGOING_PROCESSED_FILTER') ?>

                                <div class="checkbox">
                                    <label>
                                        <input type="checkbox" name="successful" value="1" checked="checked">
                                        <?= $this->translate('OUTGOING_SUCCESSFUL_FILTER') ?>
                                    </label>
                                </div>
                                <div class="checkbox">
                                    <label>
                                        <input type="checkbox" name="erroneous" value="1" checked="checked">
                                        <?= $this->translate('OUTGOING_ERRONEOUS_FILTER') ?>
                                    </label>
                                </div>
                            </label>
                        </div>
                        <button class="btn btn-default" onclick="applyFilter()">
                            <?= $this->translate('Apply filter') ?>
                        </button>
                    </div>
                </div>
            </div>
        </div>

        <div class="col-sm-9">
            <div id="table-outgoing"></div>
        <div>
    </div>
</div>

<script>
    function applyFilter() {
        var filters = [
            'status=' + $('.button-panel input[name="status"]:checked').val(),
            'successful=' + ($('.button-panel input[name="successful"]').prop('checked') ? 1 : 0),
            'erroneous=' + ($('.button-panel input[name="erroneous"]').prop('checked') ? 1 : 0),
        ];
        var url = '<?= $this->basePath('/admin/outgoing/outgoing-table') ?>'
            + '?' + filters.join('&');

        $('#table-outgoing').dynamicTable({
            url: url,
            row_id_column: 'id',
            sort_column: 'id',
            sort_dir: 'desc',
            loader_image: '<?= $this->basePath('/img/loader.gif') ?>',
            strings: dynamicTableStrings,
            mapper: function (row) {
                if (row['when_sent'] != null) {
                    var m = moment.unix(row['when_sent']).local();
                    row['when_sent'] = m.format('<?= $this->translate('GENERIC_MOMENT_FORMAT') ?>');
                }

                return row;
            },
        });
    }

    var tour = new Tour({
        name: 'outgoing',
        template: '<?= $this->translate('TOUR_TEMPLATE') ?>',
        steps: [
            {
                element: "#table-outgoing",
                placement: "left",
                title: "<?= str_replace('"', "'", $this->translate('Outgoing')) ?>",
                content: "<?= str_replace('"', "'", $this->translate('TOUR_OUTGOING_INTRO')) ?>"
            },
        ],
    });

    $(document).ready(function () {
        applyFilter();
        tour.init().start();
        $('#tour-button')
            .on('click', function () { tour.restart(); })
            .parent().show();
    });
</script>
