<?php

    $this->layout()->activePage = 'parser';

?>

<div class="container">
    <div class="row">
        <div class="col-sm-12">
            <h3><span id="page-title"><?= $this->translate('Message parser variables') ?></span></h3>
        </div>
    </div>

    <div class="row">
        <div class="col-sm-7">
            <?php foreach ($this->variables as $name => $props): ?>
                <div class="row">
                    <hr>
                </div>
                <div class="row">
                    <div class="col-sm-2">
                        <p class="parser-variable">$<?= $this->escapeHtml($name) ?></p>
                    </div>
                    <div class="col-sm-5">
                        <p><?= $this->translate($props['descr']) ?></p>
                    </div>
                </div>
            <?php endforeach ?>
        </div>

        <div class="col-sm-5">
            <div class="panel panel-default">
                <div class="panel-heading">
                    <h3 class="panel-title">
                        <?= $this->translate('PARSER_SYNTAX_TITLE') ?>
                    </h3>
                </div>
                <div class="panel-body">
                    <p><?= $this->translate('PARSER_SYNTAX_BODY') ?></p>
                </div>
            </div>
        </div>
    </div>
</div>
