<?php

    $this->layout()->activePage = 'parser';

?>
<div class="container">
    <div class="row">
        <div class="col-sm-12">
            <h3><span id="page-title"><?= $this->translate('Message parser functions') ?></span></h3>
        </div>
    </div>

    <div class="row">
        <div class="col-sm-7">
            <?php foreach ($this->functions as $name => $props): ?>
                <div class="row">
                    <hr>
                </div>
                <div class="row">
                    <div class="col-sm-3">
                        <p class="parser-function"><?= $this->escapeHtml($name) ?></p>
                    </div>
                    <div class="col-sm-9">
                        <p class="parser-descr"><?= $this->translate($props['descr']) ?></p>
                    </div>
                </div>
            <?php endforeach ?>
        </div>

        <div class="col-sm-5">
            <div class="panel panel-default">
                <div class="panel-heading">
                    <h3 id="syntax-title" class="panel-title">
                        <?= $this->translate('PARSER_SYNTAX_TITLE') ?>
                    </h3>
                </div>
                <div class="panel-body">
                    <p><?= $this->translate('PARSER_SYNTAX_BODY') ?></p>
                </div>
            </div>

            <hr>

            <div class="panel panel-default">
                <div class="panel-heading">
                    <h3 class="panel-title">
                        <?= $this->translate('AVAILABLE_FORMS_TITLE') ?>
                    </h3>
                </div>
                <div class="panel-body">
                    <p><?= $this->translate('AVAILABLE_FORMS_BODY') ?></p>
                    <dl class="dl-horizontal">
                        <?php foreach ($this->dataForms as $name => $props): ?>
                            <dt><?= $this->escapeHtml($name) ?></dt>
                            <dd><?= $this->translate($props['title']) ?></dd>
                        <?php endforeach ?>
                    </dl>
                </div>
            </div>
        </div>
    </div>
</div>

<script>
    var tour = new Tour({
        name: 'parser',
        template: '<?= $this->translate('TOUR_TEMPLATE') ?>',
        steps: [
            {
                element: "#syntax-title",
                placement: "left",
                title: "<?= str_replace('"', "'", $this->translate('Parser')) ?>",
                content: "<?= str_replace('"', "'", $this->translate('TOUR_PARSER_INTRO')) ?>"
            },
            {
                element: "#mailbox-navbar",
                placement: "bottom",
                title: "<?= str_replace('"', "'", $this->translate('Parser')) ?>",
                content: "<?= str_replace('"', "'", $this->translate('TOUR_PARSER_MAIL')) ?>"
            },
        ],
    });

    $(document).ready(function () {
        tour.init().start();
        $('#tour-button')
            .on('click', function () { tour.restart(); })
            .parent().show();
    });
</script>
