<?php

    $this->layout()->activePage = 'import-export';

?>
<div class="container">
    <div class="row">
        <div class="col-sm-12">
            <h1><span id="page-title"><?= $this->translate('Import preview') ?></span></h1>
        </div>
    </div>

    <div class="row">
        <div class="col-sm-12">
            <div id="table-preview"></div>
            <script>
                $('#table-preview').dynamicTable({
                    url: '<?= $this->basePath('/admin/import-export/preview-table') ?>',
                    row_id_column: null,
                    sort_column: 'email',
                    sort_dir: 'asc',
                    loader_image: '<?= $this->basePath('/img/loader.gif') ?>',
                    strings: dynamicTableStrings,
                    mapper: function (row) {
                        return row;
                    },
                });
            </script>
        <div>
    </div>

    <div class="row">
        <div class="col-sm-12">
            <p>
                <?= $this->translate('Data will be imported into the following groups') ?>:
                <?= count($this->groups) == 0 ? $this->translate('(No group)') : join(', ', $this->groups) ?>
            </p>
        </div>
    </div>

    <div class="row">
        <div class="col-sm-12">
            <a href="<?= $this->basePath('/admin/import-export/accept-import') ?>"  class="btn btn-primary">
                <?= $this->translate('Accept results') ?>
            </a>
            <a href="<?= $this->basePath('/admin/import-export/cancel-import') ?>"  class="btn btn-default">
                <?= $this->translate('Cancel import') ?>
            </a>
        </div>
    </div>
</div>
