<?php

    $this->layout()->activePage = 'import-export';

?>

<div class="container">
    <div class="row">
        <div class="col-sm-12">
            <h1><span id="page-title"><?= $this->translate('Import/Export') ?></span></h1>
        </div>
    </div>

    <div class="row">
        <div class="col-sm-3">
            <div id="presets-panel" class="panel panel-default">
                <div class="panel-heading">
                    <h3 class="panel-title"><?= $this->translate('Presets') ?></h3>
                </div>
                <div id="presets" class="list-group">
                    <a href="javascript:void(0)" class="list-group-item"
                       data-name="minimum" onclick="loadPreset($(this))">
                        <?= $this->translate('IMPORT_EXPORT_MINIMUM') ?>
                    </a>
                    <a href="javascript:void(0)" class="list-group-item"
                       data-name="full-name" onclick="loadPreset($(this))">
                        <?= $this->translate('IMPORT_EXPORT_FULL_NAME') ?>
                    </a>
                    <a href="javascript:void(0)" class="list-group-item"
                       data-name="maximum" onclick="loadPreset($(this))">
                        <?= $this->translate('IMPORT_EXPORT_MAXIMUM') ?>
                    </a>
                </div>
            </div>
        </div>

        <div class="col-sm-3">
            <div id="available-panel" class="panel panel-default">
                <div class="panel-heading">
                    <h3 class="panel-title"><?= $this->translate('Available fields') ?></h3>
                </div>
                <div class="panel-body button-panel">
                    <div class="checkbox" data-var="email">
                        <label>
                            <input type="checkbox" onclick="toggleField($(this))">
                            <span class="text">email</span>
                        </label>
                    </div>
                    <?php foreach ($this->forms as $formName => $formProps): ?>
                        <?php foreach ($formProps['fields'] as $var): ?>
                            <div class="checkbox" data-var="<?= $formName ?>-<?= $var ?>">
                                <label>
                                    <input type="checkbox" onclick="toggleField($(this))">
                                    <span class="text"><?= $formName ?> / <?= $var ?></span>
                                </label>
                            </div>
                        <?php endforeach ?>
                    <?php endforeach ?>
                </div>
            </div>
        </div>

        <div class="col-sm-3">
            <div id="selected-panel" class="panel panel-default">
                <div class="panel-heading">
                    <h3 class="panel-title"><?= $this->translate('Reorder columns') ?></h3>
                </div>
                <div class="panel-body button-panel">
                </div>
            </div>
        </div>

        <div class="col-sm-3">
            <div id="format-panel" class="panel panel-default">
                <div class="panel-heading">
                    <h3 class="panel-title"><?= $this->translate('File format') ?></h3>
                </div>
                <div class="panel-body button-panel">
                    <div class="radio">
                        <label>
                            <input type="radio" name="format" value="excel">
                            <?= $this->translate('Excel format') ?>
                        </label>
                    </div>
                    <div class="radio">
                        <label>
                            <input type="radio" name="format" value="csv" checked="checked">
                            <?= $this->translate('CSV format') ?>
                            <div id="csv-options">
                                <br>
                                <div class="group-title"><?= $this->translate('Field separator') ?>:</div>
                                <div class="radio">
                                    <label>
                                        <input type="radio" name="separator" value="comma" checked="checked">
                                        <?= $this->translate('Comma') ?>
                                    </label>
                                </div>
                                <div class="radio">
                                    <label>
                                        <input type="radio" name="separator" value="semicolon">
                                        <?= $this->translate('Semicolon') ?>
                                    </label>
                                </div>
                                <div class="radio">
                                    <label>
                                        <input type="radio" name="separator" value="tab">
                                        <?= $this->translate('Tab') ?>
                                    </label>
                                </div>
                                <br>
                                <div class="group-title"><?= $this->translate('Line endings') ?>:</div>
                                <div class="radio">
                                    <label>
                                        <input type="radio" name="ending" value="windows" checked="checked">
                                        <?= $this->translate('Windows') ?>
                                    </label>
                                </div>
                                <div class="radio">
                                    <label>
                                        <input type="radio" name="ending" value="unix">
                                        <?= $this->translate('Unix') ?>
                                    </label>
                                </div>
                                <br>
                                <div class="group-title"><?= $this->translate('Encoding') ?>:</div>
                                <select name="encoding" class="form-control">
                                    <?php foreach ($this->encodings as $key => $value): ?>
                                        <option value="<?= $key ?>"><?= $this->escapeHtml($value) ?></option>
                                    <?php endforeach ?>
                                </select>
                            </div>
                        </label>
                    </div>
                    <br>
                    <button type="button" class="btn btn-default" onclick="uploadFile()">
                        <?= $this->translate('Import') ?>
                    </button>
                    <hr>
                    <button type="button" class="btn btn-default" onclick="downloadFile()">
                        <?= $this->translate('Export') ?>
                    </button>
                </div>
            </div>
        </div>
    </div>
</div>

<div id="templates" style="display: none">
    <div class="drag-n-drop" data-var="form-field">
        <span class="glyphicon glyphicon-menu-hamburger"></span>
        <span class="text"></span>
    </div>
</div>

<script>
    function clearFields() {
        $('#selected-panel .panel-body').empty();
        $('#available-panel input').prop('checked', false);
    }

    function addField(name) {
        var existing = $('#selected-panel div[data-var="' + name + '"]');
        if (existing.length)
            return;

        var div = $('#templates .drag-n-drop').clone();
        var title = name.split('-');

        div.attr('data-var', name)
           .find('.text').text(title.length == 1 ? title[0] : title[0] + ' / ' + title[1]);
        div.appendTo($('#selected-panel .panel-body'));

        var available = $('#available-panel div[data-var="' + name + '"]');
        available.find('input').prop('checked', true);
    }

    function removeField(name) {
        $('#selected-panel div[data-var="' + name + '"]').remove();
    }

    function toggleField(el) {
        var div = el.closest('.checkbox');
        if (el.prop('checked'))
            addField(div.attr('data-var'));
        else
            removeField(div.attr('data-var'));

        $('#presets-panel a').removeClass('active');
    }

    function loadPreset(el) {
        clearFields();
        switch (el.attr('data-name')) {
            case 'minimum':
                addField('email', 'email');
                break;
            case 'full-name':
                addField('email', 'email');
                addField('profile-first_name');
                addField('profile-middle_name');
                addField('profile-last_name');
                break;
            case 'maximum':
                addField('email', 'email');
                addField('profile-when_updated');
                addField('profile-first_name');
                addField('profile-middle_name');
                addField('profile-last_name');
                addField('profile-gender');
                addField('profile-company');
                addField('profile-position');
                addField('subscription-when_updated');
                addField('subscription-unsubscribed');
                addField('subscription-ignored_tags');
                break;
        }
        $('#presets-panel a').removeClass('active');
        el.addClass('active');
    }

    function downloadFile()
    {
        var fields = [];
        $('#selected-panel .drag-n-drop').each(function (index, element) {
            fields.push($(element).attr('data-var'));
        });

        $.ajax({
            url: '<?= $this->basePath('/admin/import-export/download') ?>',
            data: {
                fields: fields.join(','),
                format: $('#format-panel [name="format"]:checked').val(),
                separator: $('#format-panel [name="separator"]:checked').val(),
                ending: $('#format-panel [name="ending"]:checked').val(),
                encoding: $('#format-panel [name="encoding"]').val(),
            },
            success: function (html) {
                var modal = $('#modal-form');
                modal.find('.modal-title').text('<?= $this->translate('Export data') ?>');
                modal.find('button[type=submit]').text('<?= $this->translate('Download') ?>');
                modal.find('.modal-body').html(html);
            }
        });
    }

    function uploadFile()
    {
        var fields = [];
        $('#selected-panel .drag-n-drop').each(function (index, element) {
            fields.push($(element).attr('data-var'));
        });

        $.ajax({
            url: '<?= $this->basePath('/admin/import-export/upload') ?>',
            data: {
                fields: fields.join(','),
                format: $('#format-panel [name="format"]:checked').val(),
                separator: $('#format-panel [name="separator"]:checked').val(),
                ending: $('#format-panel [name="ending"]:checked').val(),
                encoding: $('#format-panel [name="encoding"]').val(),
            },
            success: function (html) {
                var modal = $('#modal-form');
                modal.find('.modal-title').text('<?= $this->translate('Import data') ?>');
                modal.find('button[type=submit]').text('<?= $this->translate('Preview') ?>');
                modal.find('.modal-body').html(html);
            }
        });
    }

    $('#selected-panel .panel-body').sortable();
    $('#selected-panel .panel-body').disableSelection();
    $('#format-panel input[name="format"]').on('change', function () {
        var value = $(this).val();
        if (value == 'csv')
            $('#csv-options').show();
        else
            $('#csv-options').hide();
    });

    var tour = new Tour({
        name: 'import-export',
        template: '<?= $this->translate('TOUR_TEMPLATE') ?>',
        steps: [
            {
                element: "#presets",
                placement: "right",
                title: "<?= str_replace('"', "'", $this->translate('Import/Export')) ?>",
                content: "<?= str_replace('"', "'", $this->translate('TOUR_IMPORT_EXPORT_INTRO')) ?>"
            },
        ]
    });

    $(document).ready(function () {
        tour.init().start();
        $('#tour-button')
            .on('click', function () { tour.restart(); })
            .parent().show();
    });
</script>
