<?php

if ($this->script) {    // Run script and return (no form is displayed)
    echo "<script>" . PHP_EOL;
    echo $this->script . PHP_EOL;
    echo "</script>" . PHP_EOL;
    return;
}

$form = $this->form;
$security = $form->get('security');
$fields = $form->get('fields');
$format = $form->get('format');
$separator = $form->get('separator');
$ending = $form->get('ending');
$encoding = $form->get('encoding');
$groups = $form->get('groups');
$file = $form->get('file');

?>

<?php if ($fields->getValue() == ''): ?>
    <script>
        bsAlert('<?= $this->translate('IMPORT_EXPORT_NO_FIELDS') ?>');
    </script>
    <?php return ?>
<?php elseif (!$this->hasEmail): ?>
    <script>
        bsAlert('<?= $this->translate('IMPORT_NO_EMAIL') ?>');
    </script>
    <?php return ?>
<?php else: ?>
    <form class="form-horizontal" name="<?= $form->getName() ?>" onsubmit="return false"
          method="<?= $form->getAttribute('method') ?>"
          enctype="multipart/form-data"
          action="<?= $this->basePath('/admin/import-export/upload') ?>">

        <input type="hidden"
               name="<?= $security->getName() ?>"
               value="<?= $security->getValue() ?>">

        <input type="hidden"
               name="<?= $fields->getName() ?>"
               value="<?= $fields->getValue() ?>">

        <input type="hidden"
               name="<?= $format->getName() ?>"
               value="<?= $format->getValue() ?>">

        <input type="hidden"
               name="<?= $separator->getName() ?>"
               value="<?= $separator->getValue() ?>">

        <input type="hidden"
               name="<?= $ending->getName() ?>"
               value="<?= $ending->getValue() ?>">

        <input type="hidden"
               name="<?= $encoding->getName() ?>"
               value="<?= $encoding->getValue() ?>">

        <?php foreach (array_merge($this->messages, $security->getMessages()) as $msg): ?>
            <div class="alert alert-danger">
                <center><?= $this->escapeHtml($this->translate($msg)) ?></center>
            </div>
        <?php endforeach ?>

        <?php $valid = count($groups->getMessages()) == 0 ?>
        <div class="form-group <?= $valid ? '' : 'has-error' ?>">
            <label class="col-sm-4 control-label" for="<?= $groups->getName() ?>">
                <?= $this->escapeHtml($this->translate($groups->getLabel())) ?>:
            </label>
            <div class="col-sm-8">
                <?php foreach ($groups->getValueOptions() as $value => $label): ?>
                    <div class="checkbox">
                        <label>
                            <input type="checkbox"
                                   name="<?= $groups->getName() ?>[]"
                                   value="<?= $this->escapeHtml($value) ?>"
                                   <?= in_array($value, $groups->getValue()) ? 'checked="checked"' : '' ?>
                                   data-on-enter="$('#modal-form button[type=submit]').focus().click()">
                            <?= $this->escapeHtml($label) ?>
                        </label>
                    </div>
                <?php endforeach ?>
                <div class="help-block">
                    <?php if (!$valid): ?>
                        <ul class="list-unstyled icon-list error-list">
                        <?php foreach ($groups->getMessages() as $msg): ?>
                            <li><?= $this->escapeHtml($msg) ?></li>
                        <?php endforeach ?>
                        </ul>
                    <?php endif ?>
                </div>
            </div>
        </div>

        <?php $valid = count($file->getMessages()) == 0 ?>
        <div class="form-group <?= $valid ? '' : 'has-error' ?>">
            <label class="col-sm-4 control-label" for="<?= $file->getName() ?>">
                <?= $this->escapeHtml($this->translate($file->getLabel())) ?>:
                <span class="required-marker text-danger">
                    <?= $this->translate('REQUIRED FIELD') ?>
                </span>
            </label>
            <div class="col-sm-8">
                <input type="file" class="form-control"
                       name="<?= $file->getName() ?>"
                       data-on-blur="validateFormField($('#modal-form [name=<?= $file->getName() ?>]'))"
                       data-on-enter="$('#modal-form button[type=submit]').focus().click()">
                <div class="help-block">
                    <?php if (!$valid): ?>
                        <ul class="list-unstyled icon-list error-list">
                        <?php foreach ($file->getMessages() as $msg): ?>
                            <li><?= $this->escapeHtml($msg) ?></li>
                        <?php endforeach ?>
                        </ul>
                    <?php endif ?>
                </div>
            </div>
        </div>
    </form>
<?php endif ?>

<script>
    var modal = $('#modal-form');

    initModalForm(modal);                   // See /js/app.js 

    if (!modal.is(':visible'))
        modal.modal('show');

    setFormFocus(modal.find('form'));       // See /js/app.js
</script>
