<?php

    $this->layout()->activePage = 'index';

?>

<div class="container extra-top-margin">
    <div class="row">
        <div class="col-sm-6">
            <ol class="breadcrumb">
                <li><?= $this->translate('Mail') ?></li>
                <li><?= $this->translate('Message parser') ?></li>
            </ol>
            <p class="breadcrumb-help-block"><?= $this->translate('MESSAGE_PARSER_HELP') ?></p>

            <hr>
            <ol class="breadcrumb">
                <li><?= $this->translate('Mail') ?></li>
                <li><?= $this->translate('Mailbox') ?></li>
            </ol>
            <p class="breadcrumb-help-block"><?= $this->translate('MAILBOX_HELP') ?></p>
            <hr>
            <ol class="breadcrumb">
                <li><?= $this->translate('Mail') ?></li>
                <li><?= $this->translate('Outgoing messages') ?></li>
            </ol>
            <p class="breadcrumb-help-block"><?= $this->translate('OUTGOING_HELP') ?></p>

            <hr>
            <ol class="breadcrumb">
                <li><?= $this->translate('Campaign') ?></li>
                <li><?= $this->translate('Client groups') ?></li>
            </ol>
            <p class="breadcrumb-help-block"><?= $this->translate('GROUPS_HELP') ?></p>

            <hr>
            <ol class="breadcrumb">
                <li><?= $this->translate('Campaign') ?></li>
                <li><?= $this->translate('Clients') ?></li>
            </ol>
            <p class="breadcrumb-help-block"><?= $this->translate('CLIENTS_HELP') ?></p>

            <hr>
            <ol class="breadcrumb">
                <li><?= $this->translate('Campaign') ?></li>
                <li><?= $this->translate('Mail campaigns') ?></li>
            </ol>
            <p class="breadcrumb-help-block"><?= $this->translate('CAMPAIGNS_HELP') ?></p>
        </div>

        <div class="col-sm-6">
            <div class="panel panel-default">
                <div class="panel-heading">
                    <h3 class="panel-title"><?= $this->translate('Mail campaigns') ?></h3>
                </div>
                <div class="panel-body">
                    <table class="table table-condensed table-striped table-hover">
                        <tbody>
                            <?php foreach ($this->statuses as $status => $count): ?>
                                <tr>
                                    <td><?= $this->translate('STATUS_' . strtoupper($status)) ?></td>
                                    <td><span class="badge"><?= $count ?></span></td>
                                </tr>
                            <?php endforeach ?>
                        </tbody>
                    </table>
                </div>
            </div>

            <div class="panel panel-default">
                <div class="panel-heading">
                    <h3 class="panel-title"><?= $this->translate('Important log messages') ?></h3>
                </div>
                <div class="panel-body">
                    <table class="table table-condensed table-striped table-hover">
                        <thead>
                            <tr>
                                <th><?= $this->translate('Date') ?></th>
                                <th><?= $this->translate('Message') ?></th>
                            </tr>
                        </thead>
                        <tbody>
                            <?php if (count($this->log) == 0): ?>
                                <tr>
                                    <td colspan="2" class="empty-table">
                                        <?= $this->translate('No messages') ?>
                                    </td>
                                </tr>
                            <?php else: ?>
                                <?php foreach ($this->log as $entry): ?>
                                    <tr>
                                        <td><?= $entry['when'] ?></td>
                                        <td><?= $entry['msg'] ?></td>
                                    </tr>
                                <?php endforeach ?>
                            <?php endif ?>
                        </tbody>
                    </table>
                </div>
            </div>

            <ol class="breadcrumb">
                <li><?= $this->translate('Data forms') ?></li>
            </ol>
            <p class="breadcrumb-help-block"><?= $this->translate('DATA_FORMS_HELP') ?></p>

            <hr>
            <ol class="breadcrumb">
                <li><?= $this->translate('Settings') ?></li>
                <li><?= $this->translate('Mailbox') ?></li>
            </ol>
            <p class="breadcrumb-help-block"><?= $this->translate('SETTINGS_MAILBOX_HELP') ?></p>
        </div>
    </div>
</div>
