<?php

    $this->layout()->activePage = 'index';

?>

<div class="container extra-top-margin">
    <div class="row">
        <div class="col-sm-6">
            <h3 class="page-title"><?= $this->translate('Introduction') ?></h3>
            <p><?= $this->translate('CORPNEWS_INTRO') ?></p>
        </div>

        <div class="col-sm-6">
            <div class="panel panel-default">
                <div class="panel-heading">
                    <h3 class="panel-title"><?= $this->translate('Mail campaigns') ?></h3>
                </div>
                <div class="panel-body">
                    <table class="table table-condensed table-striped table-hover">
                        <tbody>
                            <?php foreach ($this->statuses as $status => $count): ?>
                                <tr>
                                    <td><?= $this->translate('STATUS_' . strtoupper($status)) ?></td>
                                    <td><?= $count ?></td>
                                </tr>
                            <?php endforeach ?>
                        </tbody>
                    </table>
                </div>
            </div>

            <div class="panel panel-default">
                <div class="panel-heading">
                    <h3 class="panel-title"><?= $this->translate('Important log messages') ?></h3>
                </div>
                <div class="panel-body">
                    <table class="table table-condensed table-striped table-hover">
                        <thead>
                            <tr>
                                <th><?= $this->translate('Date') ?></th>
                                <th><?= $this->translate('Message') ?></th>
                            </tr>
                        </thead>
                        <tbody>
                            <?php if (count($this->log) == 0): ?>
                                <tr>
                                    <td colspan="2" class="empty-table">
                                        <?= $this->translate('No messages') ?>
                                    </td>
                                </tr>
                            <?php else: ?>
                                <?php foreach ($this->log as $entry): ?>
                                    <tr>
                                        <td><?= $entry['when'] ?></td>
                                        <td><?= $entry['msg'] ?></td>
                                    </tr>
                                <?php endforeach ?>
                            <?php endif ?>
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>
