<?php

    $this->layout()->activePage = 'document';

?>
<div class="container">
    <div class="row">
        <div class="col-sm-offset-3 col-sm-9">
            <h1><span id="page-title"><?= $this->translate('Data forms') ?></span></h1>
        </div>
    </div>

    <div class="row">
        <div class="col-sm-3">
            <div data-sidebar="sm">
                <div id="actions-panel" class="panel panel-default">
                    <div class="panel-heading">
                        <h3 class="panel-title"><?= $this->translate('Available data forms') ?></h3>
                    </div>
                    <div class="list-group">
                        <?php foreach ($this->dataForms as $name => $title): ?>
                            <a href="<?= $this->basePath('/form/' . $name) ?>"
                                class="list-group-item <?= $name == $this->current ? 'active' : '' ?>">
                                <?= $this->translate($title) ?>
                            </a>
                        <?php endforeach ?>
                    </div>
                </div>
            </div>
        </div>

        <div class="col-sm-9">
            <div id="table-documents"></div>
            <script>
                $('#table-documents').dynamicTable({
                    url: '<?= $this->basePath('/admin/document/document-table?name=' . $this->current) ?>',
                    row_id_column: 'email',
                    sort_column: 'email',
                    sort_dir: 'asc',
                    loader_image: '<?= $this->basePath('/img/loader.gif') ?>',
                    strings: dynamicTableStrings,
                    mapper: function (row) {
                        if (row['when_updated'] != null) {
                            var m = moment.unix(row['when_updated']).local();
                            row['when_updated'] = m.format('YYYY-MM-DD HH:mm:ss Z');
                        }

                        return row;
                    },
                });
            </script>
        <div>
    </div>
</div>

<script>
    function reloadTable() {
        var table = $('#table-documents').data('dynamicTable');
        table.refresh();
    }
</script>
